<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Public Health | Machine Learning Application in Industry</title>
  <meta name="description" content="This is guide for Product Team Algoritma." />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Public Health | Machine Learning Application in Industry" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is guide for Product Team Algoritma." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Public Health | Machine Learning Application in Industry" />
  
  <meta name="twitter:description" content="This is guide for Product Team Algoritma." />
  

<meta name="author" content="Algoritma Team" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="bioinformatics.html"/>
<link rel="next" href="media.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/htmlwidgets-1.5.1/htmlwidgets.js"></script>
<link href="libs/wordcloud2-0.0.1/wordcloud.css" rel="stylesheet" />
<script src="libs/wordcloud2-0.0.1/wordcloud2-all.js"></script>
<script src="libs/wordcloud2-0.0.1/hover.js"></script>
<script src="libs/wordcloud2-binding-0.2.1/wordcloud2.js"></script>
<link href="libs/plot_text_explanations-0.1.0/plot_text_explanations.css" rel="stylesheet" />
<script src="libs/plot_text_explanations-binding-0.5.1/plot_text_explanations.js"></script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="assets\book.css" type="text/css" />
<link rel="stylesheet" href="https:\\use.fontawesome.com\releases\v5.3.1\css\all.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Algoritma Book</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="telecommunication.html"><a href="telecommunication.html"><i class="fa fa-check"></i><b>2</b> Telecommunication</a><ul>
<li class="chapter" data-level="2.1" data-path="telecommunication.html"><a href="telecommunication.html#customer-churn-prediction"><i class="fa fa-check"></i><b>2.1</b> Customer Churn Prediction</a><ul>
<li class="chapter" data-level="2.1.1" data-path="telecommunication.html"><a href="telecommunication.html#background"><i class="fa fa-check"></i><b>2.1.1</b> Background</a></li>
<li class="chapter" data-level="2.1.2" data-path="telecommunication.html"><a href="telecommunication.html#modelling-analysis"><i class="fa fa-check"></i><b>2.1.2</b> Modelling Analysis</a></li>
<li class="chapter" data-level="2.1.3" data-path="telecommunication.html"><a href="telecommunication.html#conclusion"><i class="fa fa-check"></i><b>2.1.3</b> Conclusion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="finance.html"><a href="finance.html"><i class="fa fa-check"></i><b>3</b> Finance</a><ul>
<li class="chapter" data-level="3.1" data-path="finance.html"><a href="finance.html#credit-risk-analysis"><i class="fa fa-check"></i><b>3.1</b> Credit Risk Analysis</a><ul>
<li class="chapter" data-level="3.1.1" data-path="finance.html"><a href="finance.html#background-1"><i class="fa fa-check"></i><b>3.1.1</b> Background</a></li>
<li class="chapter" data-level="3.1.2" data-path="finance.html"><a href="finance.html#modelling-analysis-1"><i class="fa fa-check"></i><b>3.1.2</b> Modelling Analysis</a></li>
<li class="chapter" data-level="3.1.3" data-path="finance.html"><a href="finance.html#recommendation"><i class="fa fa-check"></i><b>3.1.3</b> Recommendation</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="finance.html"><a href="finance.html#evaluating-customer-financial-complaints"><i class="fa fa-check"></i><b>3.2</b> Evaluating Customer Financial Complaints</a><ul>
<li class="chapter" data-level="3.2.1" data-path="finance.html"><a href="finance.html#background-2"><i class="fa fa-check"></i><b>3.2.1</b> Background</a></li>
<li class="chapter" data-level="3.2.2" data-path="finance.html"><a href="finance.html#exploratory-data-analysis-1"><i class="fa fa-check"></i><b>3.2.2</b> Exploratory Data Analysis</a></li>
<li class="chapter" data-level="3.2.3" data-path="finance.html"><a href="finance.html#comparing-sentiment-dictionaries"><i class="fa fa-check"></i><b>3.2.3</b> Comparing Sentiment Dictionaries</a></li>
<li class="chapter" data-level="3.2.4" data-path="finance.html"><a href="finance.html#correlation-pairs"><i class="fa fa-check"></i><b>3.2.4</b> Correlation Pairs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="retail.html"><a href="retail.html"><i class="fa fa-check"></i><b>4</b> Retail</a><ul>
<li class="chapter" data-level="4.1" data-path="retail.html"><a href="retail.html#e-commerce-clothing-reviews"><i class="fa fa-check"></i><b>4.1</b> E-Commerce Clothing Reviews</a><ul>
<li class="chapter" data-level="4.1.1" data-path="retail.html"><a href="retail.html#background-3"><i class="fa fa-check"></i><b>4.1.1</b> Background</a></li>
<li class="chapter" data-level="4.1.2" data-path="retail.html"><a href="retail.html#cleaning-data"><i class="fa fa-check"></i><b>4.1.2</b> Cleaning Data</a></li>
<li class="chapter" data-level="4.1.3" data-path="retail.html"><a href="retail.html#modelling-2"><i class="fa fa-check"></i><b>4.1.3</b> Modelling</a></li>
<li class="chapter" data-level="4.1.4" data-path="retail.html"><a href="retail.html#visualize-data-text"><i class="fa fa-check"></i><b>4.1.4</b> Visualize Data Text</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="insurance.html"><a href="insurance.html"><i class="fa fa-check"></i><b>5</b> Insurance</a><ul>
<li class="chapter" data-level="5.1" data-path="insurance.html"><a href="insurance.html#prediction-of-total-claim-amount"><i class="fa fa-check"></i><b>5.1</b> Prediction of Total Claim Amount</a><ul>
<li class="chapter" data-level="5.1.1" data-path="insurance.html"><a href="insurance.html#background-4"><i class="fa fa-check"></i><b>5.1.1</b> Background</a></li>
<li class="chapter" data-level="5.1.2" data-path="insurance.html"><a href="insurance.html#modelling-analysis-2"><i class="fa fa-check"></i><b>5.1.2</b> Modelling Analysis</a></li>
<li class="chapter" data-level="5.1.3" data-path="insurance.html"><a href="insurance.html#conclusion-1"><i class="fa fa-check"></i><b>5.1.3</b> Conclusion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="bioinformatics.html"><a href="bioinformatics.html"><i class="fa fa-check"></i><b>6</b> Bioinformatics</a><ul>
<li class="chapter" data-level="6.1" data-path="bioinformatics.html"><a href="bioinformatics.html#qtl-mapping-for-disease-resistance"><i class="fa fa-check"></i><b>6.1</b> QTL Mapping for Disease Resistance</a><ul>
<li class="chapter" data-level="6.1.1" data-path="bioinformatics.html"><a href="bioinformatics.html#backgorund"><i class="fa fa-check"></i><b>6.1.1</b> Backgorund</a></li>
<li class="chapter" data-level="6.1.2" data-path="bioinformatics.html"><a href="bioinformatics.html#modelling-analysis-3"><i class="fa fa-check"></i><b>6.1.2</b> Modelling Analysis</a></li>
<li class="chapter" data-level="6.1.3" data-path="bioinformatics.html"><a href="bioinformatics.html#conclusion-2"><i class="fa fa-check"></i><b>6.1.3</b> Conclusion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="public-health.html"><a href="public-health.html"><i class="fa fa-check"></i><b>7</b> Public Health</a><ul>
<li class="chapter" data-level="7.1" data-path="public-health.html"><a href="public-health.html#survival-analysis-of-patients-with-lung-cancer"><i class="fa fa-check"></i><b>7.1</b> Survival Analysis of Patients with Lung Cancer</a><ul>
<li class="chapter" data-level="7.1.1" data-path="public-health.html"><a href="public-health.html#import-data-3"><i class="fa fa-check"></i><b>7.1.1</b> Import Data</a></li>
<li class="chapter" data-level="7.1.2" data-path="public-health.html"><a href="public-health.html#exploratory-data-analysis-3"><i class="fa fa-check"></i><b>7.1.2</b> Exploratory Data Analysis</a></li>
<li class="chapter" data-level="7.1.3" data-path="public-health.html"><a href="public-health.html#modelling-analysis-4"><i class="fa fa-check"></i><b>7.1.3</b> Modelling Analysis</a></li>
<li class="chapter" data-level="7.1.4" data-path="public-health.html"><a href="public-health.html#conclusion-3"><i class="fa fa-check"></i><b>7.1.4</b> Conclusion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="media.html"><a href="media.html"><i class="fa fa-check"></i><b>8</b> Media</a><ul>
<li class="chapter" data-level="8.1" data-path="media.html"><a href="media.html#causal-impact-on-leads-generation"><i class="fa fa-check"></i><b>8.1</b> Causal Impact on Leads generation</a><ul>
<li class="chapter" data-level="8.1.1" data-path="media.html"><a href="media.html#background-5"><i class="fa fa-check"></i><b>8.1.1</b> Background</a></li>
<li class="chapter" data-level="8.1.2" data-path="media.html"><a href="media.html#modelling-analysis-5"><i class="fa fa-check"></i><b>8.1.2</b> Modelling Analysis</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://algorit.ma/" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Machine Learning Application in Industry</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="public-health" class="section level1">
<h1><span class="header-section-number">Chapter 7</span> Public Health</h1>
<div id="survival-analysis-of-patients-with-lung-cancer" class="section level2">
<h2><span class="header-section-number">7.1</span> Survival Analysis of Patients with Lung Cancer</h2>
<p>Kanker paru merupakan kanker pada organ pernapasan yang menjadi kanker pembunuh nomer satu di dunia dan Indonesia (CNN Indonesia, 2018). Data internasional dari <em>Globocan</em> 2018 menyatakan kanker paru adalah kanker yang paling banyak ditemukan di pria dan wanita di seluruh dunia dibandingkan jenis kanker lainnya. Pasien penderita kanker paru memerlukan penanganan yang terarah. Oleh karena itu akan dilakukan pengamatan, faktor apa saja yang mempengaruhi waktu ketahanan hidup pasien kanker paru. Metode yang digunakan adalah <em>survival analysis</em>, yaitu analisis statistik untuk mengambil keputusan yang berkaitan dengan waktu sampai dengan terjadinya suatu kejadian khusus (<em>failure event/ end point</em>).</p>
<p>Pada bidang studi kanker, hal yang sering jadi perhatian peneliti adalah:</p>
<ul>
<li>Berapa probabilitas individu/pasien untuk survive selama 3 tahun?</li>
<li>Apakah terdapat perbedaan kemampuan survive antara kelompok demografi pasien?</li>
</ul>
<div id="import-data-3" class="section level3">
<h3><span class="header-section-number">7.1.1</span> Import Data</h3>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb130-1" title="1"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb130-2" title="2"><span class="kw">library</span>(survival)</a>
<a class="sourceLine" id="cb130-3" title="3"><span class="kw">library</span>(SurvRegCensCov)</a>
<a class="sourceLine" id="cb130-4" title="4"><span class="kw">library</span>(survminer)</a>
<a class="sourceLine" id="cb130-5" title="5"></a>
<a class="sourceLine" id="cb130-6" title="6"><span class="kw">options</span>(<span class="dt">scipen =</span> <span class="dv">9999</span>)</a></code></pre></div>
<p>Data yang digunakan merupakan data dummy rekam medis dari pasien kanker paru-paru. Sebanyak 137 pasien diobservasi dimana 128 mengalami <em>event</em> meninggal dan sisanya tersensor (dirujuk ke rumah sakit lain). Durasi waktu pengamatan menggukan satuan hari.</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb131-1" title="1">lung &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;assets/06-health/data-paru.csv&quot;</span>, <span class="dt">sep =</span> <span class="st">&quot;;&quot;</span>)</a>
<a class="sourceLine" id="cb131-2" title="2"></a>
<a class="sourceLine" id="cb131-3" title="3"><span class="kw">glimpse</span>(lung)</a></code></pre></div>
<pre><code>#&gt; Observations: 137
#&gt; Variables: 6
#&gt; $ treatment &lt;int&gt; 2, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 1, 1...
#&gt; $ survival  &lt;int&gt; 1, 1, 2, 3, 4, 7, 7, 7, 8, 8, 8, 8, 10, 10, 11...
#&gt; $ perform   &lt;int&gt; 20, 50, 40, 30, 40, 50, 20, 40, 40, 20, 80, 50...
#&gt; $ age       &lt;int&gt; 65, 35, 44, 43, 35, 72, 66, 58, 63, 61, 68, 66...
#&gt; $ status    &lt;int&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1...
#&gt; $ cell      &lt;int&gt; 4, 4, 3, 2, 3, 3, 3, 2, 4, 2, 3, 2, 4, 3, 4, 2...</code></pre>
<p>Berikut adalah penjelasan mengenai beberapa informasi yang diamati:</p>
<ol style="list-style-type: decimal">
<li><code>treatment</code>: 1 (<em>standard</em>), 2 (<em>test</em>)</li>
<li><code>cell type</code>: 1 (<em>large</em>), 2 (<em>adeno</em>), 3 (<em>small</em>), 4 (<em>squamoues</em>)</li>
<li><code>survival</code>: waktu pengamatan dalam hari</li>
<li><code>status</code>: 1 (<em>cencored</em> / berhasil survive), 0 (meninggal)</li>
</ol>
<p>Menurut Kementerian Kesehatan, kelompok usia yang paling berisiko tinggi mencakup pasien yang berusia &gt; 40 tahun. Maka, pada data akan dikelompokkan menjadi dua kelompok usia.</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb133-1" title="1">lung &lt;-<span class="st"> </span>lung <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb133-2" title="2"><span class="st">  </span><span class="kw">rename</span>(<span class="dt">time =</span> survival) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb133-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(</a>
<a class="sourceLine" id="cb133-4" title="4">    <span class="dt">treatment =</span> <span class="kw">factor</span>(treatment, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;standard&quot;</span>, <span class="st">&quot;test&quot;</span>)),</a>
<a class="sourceLine" id="cb133-5" title="5">    <span class="dt">cell =</span> <span class="kw">factor</span>(cell, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>), <span class="dt">labels =</span> <span class="kw">c</span>(<span class="st">&quot;large&quot;</span>, <span class="st">&quot;adeno&quot;</span>,<span class="st">&quot;small&quot;</span>,<span class="st">&quot;squamous&quot;</span>)),</a>
<a class="sourceLine" id="cb133-6" title="6">    <span class="dt">age =</span> <span class="kw">case_when</span>(</a>
<a class="sourceLine" id="cb133-7" title="7">      age <span class="op">&gt;</span><span class="st"> </span><span class="dv">40</span> <span class="op">~</span><span class="st"> &quot;&gt;40&quot;</span>,</a>
<a class="sourceLine" id="cb133-8" title="8">      <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> &quot;&lt;=40&quot;</span></a>
<a class="sourceLine" id="cb133-9" title="9">    )</a>
<a class="sourceLine" id="cb133-10" title="10">  )</a></code></pre></div>
</div>
<div id="exploratory-data-analysis-3" class="section level3">
<h3><span class="header-section-number">7.1.2</span> Exploratory Data Analysis</h3>
<p>Variabel prediktor (treatment, age, perform, cell) akan dianalisis menggunakan regresi survival. Dimana akan dilihat faktor-faktor apa saja yang mempengaruhi ketahanan hidup pasien sampai mengalami sebuah <em>event</em>: meninggal. Namun sebelumnya akan dianalisis menggunakan pendekatan non parametrik yaitu metode <em>Kaplan Meier</em> dan <em>Log-Rank</em>. <em>Kaplan Meier</em> adalah kurva yang menggambarkan hubungan antara waktu pengamatan (survival) dengan estimasi fungsi survival pada waktu ke-t. Kurva yang terbentuk kemudian dibandingkan menggunakan uji <em>Log Rank</em>. Tujuannya untuk mengetahui apakah terdapat perbedaan peluang survive antara level di setiap variabel kategorik.</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb134-1" title="1">lung_surv &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(<span class="dt">time =</span> time, <span class="dt">event =</span> status) <span class="op">~</span><span class="st"> </span><span class="dv">1</span>, <span class="dt">data =</span> lung)</a></code></pre></div>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb135-1" title="1"><span class="kw">tibble</span>(</a>
<a class="sourceLine" id="cb135-2" title="2">  <span class="dt">time =</span> lung_surv<span class="op">$</span>time,</a>
<a class="sourceLine" id="cb135-3" title="3">  <span class="dt">n_risk =</span> lung_surv<span class="op">$</span>n.risk,</a>
<a class="sourceLine" id="cb135-4" title="4">  <span class="dt">n_event =</span> lung_surv<span class="op">$</span>n.event,</a>
<a class="sourceLine" id="cb135-5" title="5">  <span class="dt">survival =</span> lung_surv<span class="op">$</span>surv</a>
<a class="sourceLine" id="cb135-6" title="6">)</a></code></pre></div>
<pre><code>#&gt; # A tibble: 101 x 4
#&gt;     time n_risk n_event survival
#&gt;    &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;
#&gt;  1     1    137       2    0.985
#&gt;  2     2    135       1    0.978
#&gt;  3     3    134       1    0.971
#&gt;  4     4    133       1    0.964
#&gt;  5     7    132       3    0.942
#&gt;  6     8    129       4    0.912
#&gt;  7    10    125       2    0.898
#&gt;  8    11    123       1    0.891
#&gt;  9    12    122       2    0.876
#&gt; 10    13    120       2    0.861
#&gt; # ... with 91 more rows</code></pre>
<p>Baris pertama output menyatakan pada waktu pengamatan hari pertama, ada 137 pasien, 2 diantaranya meninggal pada saat itu. Peluang survive diperoleh menggunakan perhitungan <span class="math inline">\((137-2)/137 = 0.985\)</span>. Pada garis kedua yang menyatakan observasi di hari ke-2, terdapat 135 pasien, dimana satu orang diantaranya meninggal pada saat itu. Peluang survivalnya diperoleh dengan perhitungan <span class="math inline">\((135-1)/137 = 0.978\)</span>. Tabel informasi diatas jika divisualisasikan tampilannya akan seperti berikut:</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb137-1" title="1"><span class="kw">ggsurvplot</span>(</a>
<a class="sourceLine" id="cb137-2" title="2">   lung_surv,</a>
<a class="sourceLine" id="cb137-3" title="3">   <span class="dt">color =</span> <span class="st">&quot;#2E9FDF&quot;</span>,</a>
<a class="sourceLine" id="cb137-4" title="4">   <span class="dt">ggtheme =</span> ggthemes<span class="op">::</span><span class="kw">theme_pander</span>()) <span class="op">+</span></a>
<a class="sourceLine" id="cb137-5" title="5"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Kaplan-Meier Curves all variable&quot;</span>)</a></code></pre></div>
<p><img src="bookmlindustry_files/figure-html/unnamed-chunk-108-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Hasil di atas adalah kurva survival untuk kesuluruhan parameter. Sumbu vertikal merupakan peluang survival dan sumbu horizontal adalah waktu pengamatan. Berdasarkan grafik, terlihat jelas bahwa makin jauh waktu pengamatan, peluang survive akan semakin kecil. Masing-masing variabel juga dapat dicari fungsi survivalnya, untuk memperoleh insight apakah tiap kelompok variabel terdapat perbedaan peluang survive yang signifikan.</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb138-1" title="1">km_cell &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(<span class="dt">time =</span> time, <span class="dt">event =</span> status) <span class="op">~</span><span class="st"> </span>cell, <span class="dt">data =</span> lung)</a>
<a class="sourceLine" id="cb138-2" title="2"></a>
<a class="sourceLine" id="cb138-3" title="3"><span class="kw">ggsurvplot</span>(</a>
<a class="sourceLine" id="cb138-4" title="4">   km_cell,</a>
<a class="sourceLine" id="cb138-5" title="5">   <span class="dt">ggtheme =</span> ggthemes<span class="op">::</span><span class="kw">theme_pander</span>()) <span class="op">+</span></a>
<a class="sourceLine" id="cb138-6" title="6"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Kaplan-Meier Curves for Cell Type Group&quot;</span>)</a></code></pre></div>
<p><img src="bookmlindustry_files/figure-html/unnamed-chunk-109-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Grafik diatas cukup menjelaskan bahwa keempat kelompok <em>cell type</em> memiliki perbedaan garis yang cukup signifikan. Maka, dapat diduga bahwa kelompok <em>cell type</em> pada data observasi memiliki perbedaan yang signifikan terhadap status survive pasien kanker paru. Akan dilakukan uji eksak, menggunakan <em>Log-Rank</em> untuk memperkuat identifikasi berdasarkan grafik.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb139-1" title="1"><span class="co"># log rank cell type</span></a>
<a class="sourceLine" id="cb139-2" title="2"></a>
<a class="sourceLine" id="cb139-3" title="3">lr_cell &lt;-<span class="st"> </span><span class="kw">survdiff</span>(<span class="kw">Surv</span>(time ,status)<span class="op">~</span><span class="st"> </span>cell, <span class="dt">data =</span> lung)</a>
<a class="sourceLine" id="cb139-4" title="4">lr_cell</a></code></pre></div>
<pre><code>#&gt; Call:
#&gt; survdiff(formula = Surv(time, status) ~ cell, data = lung)
#&gt; 
#&gt;                N Observed Expected (O-E)^2/E (O-E)^2/V
#&gt; cell=large    27       26     34.5      2.12      3.02
#&gt; cell=adeno    27       26     15.7      6.77      8.19
#&gt; cell=small    48       45     30.1      7.37     10.20
#&gt; cell=squamous 35       31     47.7      5.82     10.53
#&gt; 
#&gt;  Chisq= 25.4  on 3 degrees of freedom, p= 0.00001</code></pre>
<p>Tingkat signifikansi yang digunakan adalah sebesar 5% (0.05). Berdasarkan uji <em>Log-Rank</em>, diperoleh <em>p-value</em> (0.0001) &lt; alpha (0.05) maka kesimpulannya terdapat perbedaan yang signifikan pada fungsi survival keempat kelompok <em>cell</em>.</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb141-1" title="1">km_treatment &lt;-<span class="st"> </span><span class="kw">survfit</span>(<span class="kw">Surv</span>(<span class="dt">time =</span> time, <span class="dt">event =</span> status) <span class="op">~</span><span class="st"> </span>treatment, <span class="dt">data =</span> lung)</a>
<a class="sourceLine" id="cb141-2" title="2"></a>
<a class="sourceLine" id="cb141-3" title="3"><span class="kw">ggsurvplot</span>(</a>
<a class="sourceLine" id="cb141-4" title="4">   km_treatment,</a>
<a class="sourceLine" id="cb141-5" title="5">   <span class="dt">ggtheme =</span> ggthemes<span class="op">::</span><span class="kw">theme_pander</span>()) <span class="op">+</span></a>
<a class="sourceLine" id="cb141-6" title="6"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Kaplan-Meier Curves for Treatment group&quot;</span>)</a></code></pre></div>
<p><img src="bookmlindustry_files/figure-html/unnamed-chunk-111-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>Pada hasil grafik di atas, antara pria dan wanita memiliki jarak yang berdekatan. Artinya tidak terdapat perbedaan yang signifikan untuk waktu survivalnya. Untuk memperkuat interpretasi berdasarkan grafik, perlu dilakukan uji hipotesis dengan menggunakan perhitungan eksak, yakni metode Log-Rank.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb142-1" title="1"><span class="co"># log rank treatment</span></a>
<a class="sourceLine" id="cb142-2" title="2"></a>
<a class="sourceLine" id="cb142-3" title="3">lr_treatment &lt;-<span class="st"> </span><span class="kw">survdiff</span>(<span class="kw">Surv</span>(time ,status)<span class="op">~</span><span class="st"> </span>treatment, <span class="dt">data =</span> lung)</a>
<a class="sourceLine" id="cb142-4" title="4">lr_treatment</a></code></pre></div>
<pre><code>#&gt; Call:
#&gt; survdiff(formula = Surv(time, status) ~ treatment, data = lung)
#&gt; 
#&gt;                     N Observed Expected (O-E)^2/E (O-E)^2/V
#&gt; treatment=standard 69       64     64.5   0.00388   0.00823
#&gt; treatment=test     68       64     63.5   0.00394   0.00823
#&gt; 
#&gt;  Chisq= 0  on 1 degrees of freedom, p= 0.9</code></pre>
<p>Berdasarkan hasil uji <em>Log-Rank</em> diperoleh p-value (0.9) &gt; alpha (0.05) sehingga kesimpulannya tidak terdapat perbedaan yang signifikan untuk kelompok variabel treatment. Artinya baik treament standard maupun treatment test, tidak mempengaruhi waktu survive dari pasien. Adapun variabel lainnya, kelompok usia dan kelompok performa setelah di uji menggunakan <em>Log-Rank</em> diperoleh kesimpulan yang sama yakni, terdapat perbedaan waktu survive yang signifikan untuk kelompok dua variabel tersebut.</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb144-1" title="1"><span class="co"># log rank age</span></a>
<a class="sourceLine" id="cb144-2" title="2"></a>
<a class="sourceLine" id="cb144-3" title="3">lr_age &lt;-<span class="st"> </span><span class="kw">survdiff</span>(<span class="kw">Surv</span>(time ,status)<span class="op">~</span><span class="st"> </span>age, <span class="dt">data =</span> lung)</a>
<a class="sourceLine" id="cb144-4" title="4">lr_age</a></code></pre></div>
<pre><code>#&gt; Call:
#&gt; survdiff(formula = Surv(time, status) ~ age, data = lung)
#&gt; 
#&gt;            N Observed Expected (O-E)^2/E (O-E)^2/V
#&gt; age=&lt;=40  12       11     7.44     1.703      1.86
#&gt; age=&gt;40  125      117   120.56     0.105      1.86
#&gt; 
#&gt;  Chisq= 1.9  on 1 degrees of freedom, p= 0.2</code></pre>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb146-1" title="1"><span class="co"># log rank perform</span></a>
<a class="sourceLine" id="cb146-2" title="2"></a>
<a class="sourceLine" id="cb146-3" title="3">lr_perform &lt;-<span class="st"> </span><span class="kw">survdiff</span>(<span class="kw">Surv</span>(time ,status)<span class="op">~</span><span class="st"> </span>perform, <span class="dt">data =</span> lung)</a>
<a class="sourceLine" id="cb146-4" title="4">lr_perform</a></code></pre></div>
<pre><code>#&gt; Call:
#&gt; survdiff(formula = Surv(time, status) ~ perform, data = lung)
#&gt; 
#&gt;             N Observed Expected (O-E)^2/E (O-E)^2/V
#&gt; perform=10  1        1    0.463    0.6223    0.6334
#&gt; perform=20  7        7    1.037   34.2803   35.8740
#&gt; perform=30 14       14    4.957   16.4965   17.9562
#&gt; perform=40 16       15    7.686    6.9613    7.5756
#&gt; perform=50 14       13   12.155    0.0588    0.0668
#&gt; perform=60 27       26   25.341    0.0171    0.0217
#&gt; perform=70 23       21   29.832    2.6146    3.5106
#&gt; perform=75  2        2    1.522    0.1501    0.1540
#&gt; perform=80 24       22   25.989    0.6121    0.7983
#&gt; perform=85  1        1    0.845    0.0284    0.0290
#&gt; perform=90  7        6   17.460    7.5222    9.8316
#&gt; perform=99  1        0    0.713    0.7132    0.7274
#&gt; 
#&gt;  Chisq= 78.2  on 11 degrees of freedom, p= 0.000000000003</code></pre>
</div>
<div id="modelling-analysis-4" class="section level3">
<h3><span class="header-section-number">7.1.3</span> Modelling Analysis</h3>
<p>Pada analisa sebelumnya, hanya dibandingkan tiap pengamatan pasien terhadap masing-masing variabelnya saja. Kali ini akan di uji apakah pasien kanker paru-paru memiliki tingkat ketahanan hidup (survive) yang berbeda berdasarkan penyebab tipe sel, performa, dan usia pasien. Pemodelan menggunakan pendekatan 2 metode, yaitu regresi weibull dan regresi log logistik. Masing-masing hasil ringkasan informasinya dapat dilihat pada output dibawah:</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb148-1" title="1">regweibull &lt;-<span class="st"> </span><span class="kw">survreg</span>(<span class="kw">Surv</span>(time, status) <span class="op">~</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>cell <span class="op">+</span><span class="st"> </span>perform, <span class="dt">data =</span> lung, <span class="dt">dist =</span> <span class="st">&quot;weibull&quot;</span>)</a>
<a class="sourceLine" id="cb148-2" title="2"><span class="kw">summary</span>(regweibull)</a></code></pre></div>
<pre><code>#&gt; 
#&gt; Call:
#&gt; survreg(formula = Surv(time, status) ~ age + cell + perform, 
#&gt;     data = lung, dist = &quot;weibull&quot;)
#&gt;                 Value Std. Error     z              p
#&gt; (Intercept)   2.68750    0.44076  6.10 0.000000001078
#&gt; age&gt;40        0.51373    0.29711  1.73         0.0838
#&gt; celladeno    -0.78682    0.26017 -3.02         0.0025
#&gt; cellsmall    -0.42331    0.23926 -1.77         0.0769
#&gt; cellsquamous  0.29544    0.24794  1.19         0.2334
#&gt; perform       0.02945    0.00455  6.48 0.000000000092
#&gt; Log(scale)   -0.07563    0.06617 -1.14         0.2531
#&gt; 
#&gt; Scale= 0.927 
#&gt; 
#&gt; Weibull distribution
#&gt; Loglik(model)= -715.2   Loglik(intercept only)= -748.1
#&gt;  Chisq= 65.72 on 5 degrees of freedom, p= 0.0000000000008 
#&gt; Number of Newton-Raphson Iterations: 5 
#&gt; n= 137</code></pre>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb150-1" title="1">reglog &lt;-<span class="st"> </span><span class="kw">survreg</span>(<span class="kw">Surv</span>(time, status) <span class="op">~</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>cell <span class="op">+</span><span class="st"> </span>perform, <span class="dt">data =</span> lung, <span class="dt">dist =</span> <span class="st">&quot;loglogistic&quot;</span>)</a>
<a class="sourceLine" id="cb150-2" title="2"><span class="kw">summary</span>(reglog)</a></code></pre></div>
<pre><code>#&gt; 
#&gt; Call:
#&gt; survreg(formula = Surv(time, status) ~ age + cell + perform, 
#&gt;     data = lung, dist = &quot;loglogistic&quot;)
#&gt;                Value Std. Error     z                   p
#&gt; (Intercept)   2.0251     0.4312  4.70 0.00000264074529785
#&gt; age&gt;40        0.5293     0.3245  1.63              0.1028
#&gt; celladeno    -0.7763     0.2605 -2.98              0.0029
#&gt; cellsmall    -0.7438     0.2446 -3.04              0.0024
#&gt; cellsquamous -0.0388     0.2656 -0.15              0.8839
#&gt; perform       0.0359     0.0044  8.16 0.00000000000000033
#&gt; Log(scale)   -0.5509     0.0740 -7.44 0.00000000000009883
#&gt; 
#&gt; Scale= 0.576 
#&gt; 
#&gt; Log logistic distribution
#&gt; Loglik(model)= -711.3   Loglik(intercept only)= -750.3
#&gt;  Chisq= 78.02 on 5 degrees of freedom, p= 0.0000000000000022 
#&gt; Number of Newton-Raphson Iterations: 4 
#&gt; n= 137</code></pre>
<p>Kriteria yang digunakan dalam pemilihan model terbaik dilihat dari nilai <em>Akaike Information Criterion</em> (AIC). Model yang lebih layak digunakan ketika nilai AIC yang semakin rendah. AIC sangat berguna saat harus memilih model terbaik dari himpunan data yang sama. AIC yang diperoleh dari masing-masing metode:</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb152-1" title="1"><span class="kw">AIC</span>(regweibull)</a></code></pre></div>
<pre><code>#&gt; [1] 1444.466</code></pre>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb154-1" title="1"><span class="kw">AIC</span>(reglog)</a></code></pre></div>
<pre><code>#&gt; [1] 1436.513</code></pre>
<p>Model terbaik diperoleh dari model regresi log logistic, dengan AIC paling terendah yaitu 1435,513:</p>
<p><span class="math display">\[S(t|x)=\frac{1}{1 + (exp([-2.0251 + 0.5293_{age} - 0.7763_{cellAdeno} - 0.7438_{cellSmall} - 0.0388_{cellSquamous} + 0.0359_{perform})]*t)^{0.576}}\]</span></p>
<p>Jika dilakukan simulasi perhitungan peluang survive untuk dua pasien dengan karakteristik:</p>
<ul>
<li>Usia 20 tahun, cell Adeno, skor performa = 20;</li>
<li>Usia 50 tahun, cell Squamous, skor performa = 70;</li>
</ul>
<p>pada saat hari ke-100, diperoleh hasil sebagai berikut:</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb156-1" title="1"><span class="dv">1</span><span class="op">/</span>(<span class="kw">exp</span>(<span class="op">-</span><span class="fl">2.0251</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.5293</span> <span class="op">+</span><span class="st">  </span><span class="fl">0.7438</span>  <span class="op">+</span><span class="st"> </span><span class="fl">0.0359</span> <span class="op">*</span><span class="st"> </span><span class="dv">70</span>)<span class="op">*</span><span class="dv">100</span>)<span class="op">^</span><span class="fl">0.576</span></a></code></pre></div>
<pre><code>#&gt; [1] 0.02555521</code></pre>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb158-1" title="1"><span class="co"># pasien 1</span></a>
<a class="sourceLine" id="cb158-2" title="2"></a>
<a class="sourceLine" id="cb158-3" title="3"><span class="dv">1</span><span class="op">/</span>(<span class="kw">exp</span>(<span class="op">-</span><span class="fl">2.0251</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.5293</span> <span class="op">+</span><span class="st">  </span><span class="fl">0.7763</span>  <span class="op">+</span><span class="st"> </span><span class="fl">0.0359</span> <span class="op">*</span><span class="st"> </span><span class="dv">70</span>)<span class="op">*</span><span class="dv">100</span>)<span class="op">^</span><span class="fl">0.576</span></a></code></pre></div>
<pre><code>#&gt; [1] 0.02508127</code></pre>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb160-1" title="1"><span class="co"># pasien 2</span></a>
<a class="sourceLine" id="cb160-2" title="2"></a>
<a class="sourceLine" id="cb160-3" title="3"><span class="dv">1</span><span class="op">/</span>(<span class="kw">exp</span>(<span class="op">-</span><span class="fl">2.0251</span> <span class="op">+</span><span class="st"> </span><span class="fl">0.5293</span> <span class="op">+</span><span class="st">  </span><span class="fl">0.038</span>  <span class="op">+</span><span class="st"> </span><span class="fl">0.0359</span> <span class="op">*</span><span class="st"> </span><span class="dv">70</span>)<span class="op">*</span><span class="dv">100</span>)<span class="op">^</span><span class="fl">0.576</span></a></code></pre></div>
<pre><code>#&gt; [1] 0.03837407</code></pre>
<p>Maka, pasien usia lebih dari 40 tahub dengan tipe cell squamous pada saat 100 hari mengidap kanker paru peluang bertahan hidup (survive) untuk bertahan hidup lebih tinggi dibandingkan dengan tipe adino.</p>
</div>
<div id="conclusion-3" class="section level3">
<h3><span class="header-section-number">7.1.4</span> Conclusion</h3>
<p>Model regresi survival yang sesuai dengan data pengamatan adalah regresi log logistik. Faktor yang signifikan mempengaruhi laju ketahanan hidup pasien paru-paru berdasarkan data yang diamati, antara lain: usia, tipe sel, dan performa. Pasien dengan tipe sel adeno memiliki risiko paling tinggi dibandingkan lainnya. Dengan hasil pemodelan ini harapannya dapat dijadikan kajian awal untuk meningkatkan tingkat ketahanan hidup pasien paru-paru.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="bioinformatics.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="media.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"],
"google": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
},
"all": null
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
