<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 Travel and Accomodation | Machine Learning Application in Industry</title>
  <meta name="description" content="This is guide for Product Team Algoritma." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 Travel and Accomodation | Machine Learning Application in Industry" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is guide for Product Team Algoritma." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 Travel and Accomodation | Machine Learning Application in Industry" />
  
  <meta name="twitter:description" content="This is guide for Product Team Algoritma." />
  

<meta name="author" content="Algoritma Team" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="media.html"/>

<script src="libs/header-attrs-2.8/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="assets/book.css" type="text/css" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Algoritma Book</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="telecommunication.html"><a href="telecommunication.html"><i class="fa fa-check"></i><b>2</b> Telecommunication</a>
<ul>
<li class="chapter" data-level="2.1" data-path="telecommunication.html"><a href="telecommunication.html#customer-churn-prediction"><i class="fa fa-check"></i><b>2.1</b> Customer Churn Prediction</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="telecommunication.html"><a href="telecommunication.html#background"><i class="fa fa-check"></i><b>2.1.1</b> Background</a></li>
<li class="chapter" data-level="2.1.2" data-path="telecommunication.html"><a href="telecommunication.html#modelling-analysis"><i class="fa fa-check"></i><b>2.1.2</b> Modelling Analysis</a></li>
<li class="chapter" data-level="2.1.3" data-path="telecommunication.html"><a href="telecommunication.html#conclusion"><i class="fa fa-check"></i><b>2.1.3</b> Conclusion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="finance.html"><a href="finance.html"><i class="fa fa-check"></i><b>3</b> Finance</a>
<ul>
<li class="chapter" data-level="3.1" data-path="finance.html"><a href="finance.html#credit-risk-analysis"><i class="fa fa-check"></i><b>3.1</b> Credit Risk Analysis</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="finance.html"><a href="finance.html#background-1"><i class="fa fa-check"></i><b>3.1.1</b> Background</a></li>
<li class="chapter" data-level="3.1.2" data-path="finance.html"><a href="finance.html#modelling-analysis-1"><i class="fa fa-check"></i><b>3.1.2</b> Modelling Analysis</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="finance.html"><a href="finance.html#evaluating-customer-financial-complaints"><i class="fa fa-check"></i><b>3.2</b> Evaluating Customer Financial Complaints</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="finance.html"><a href="finance.html#background-2"><i class="fa fa-check"></i><b>3.2.1</b> Background</a></li>
<li class="chapter" data-level="3.2.2" data-path="finance.html"><a href="finance.html#exploratory-data-analysis"><i class="fa fa-check"></i><b>3.2.2</b> Exploratory Data Analysis</a></li>
<li class="chapter" data-level="3.2.3" data-path="finance.html"><a href="finance.html#comparing-sentiment-dictionaries"><i class="fa fa-check"></i><b>3.2.3</b> Comparing Sentiment Dictionaries</a></li>
<li class="chapter" data-level="3.2.4" data-path="finance.html"><a href="finance.html#correlation-pairs"><i class="fa fa-check"></i><b>3.2.4</b> Correlation Pairs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="retail.html"><a href="retail.html"><i class="fa fa-check"></i><b>4</b> Retail</a>
<ul>
<li class="chapter" data-level="4.1" data-path="retail.html"><a href="retail.html#e-commerce-clothing-reviews"><i class="fa fa-check"></i><b>4.1</b> E-Commerce Clothing Reviews</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="retail.html"><a href="retail.html#background-3"><i class="fa fa-check"></i><b>4.1.1</b> Background</a></li>
<li class="chapter" data-level="4.1.2" data-path="retail.html"><a href="retail.html#cleaning-data-1"><i class="fa fa-check"></i><b>4.1.2</b> Cleaning Data</a></li>
<li class="chapter" data-level="4.1.3" data-path="retail.html"><a href="retail.html#modelling-1"><i class="fa fa-check"></i><b>4.1.3</b> Modelling</a></li>
<li class="chapter" data-level="4.1.4" data-path="retail.html"><a href="retail.html#visualize-data-text"><i class="fa fa-check"></i><b>4.1.4</b> Visualize Data Text</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="retail.html"><a href="retail.html#customer-segmentation-with-rfm-analysis-in-python-programming-language"><i class="fa fa-check"></i><b>4.2</b> Customer Segmentation with RFM Analysis (in Python Programming Language)</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="retail.html"><a href="retail.html#background-4"><i class="fa fa-check"></i><b>4.2.1</b> Background</a></li>
<li class="chapter" data-level="4.2.2" data-path="retail.html"><a href="retail.html#modelling-analysis-2"><i class="fa fa-check"></i><b>4.2.2</b> Modelling Analysis</a></li>
<li class="chapter" data-level="4.2.3" data-path="retail.html"><a href="retail.html#exploratory-data-analysis-1"><i class="fa fa-check"></i><b>4.2.3</b> Exploratory Data Analysis</a></li>
<li class="chapter" data-level="4.2.4" data-path="retail.html"><a href="retail.html#modelling-2"><i class="fa fa-check"></i><b>4.2.4</b> Modelling</a></li>
<li class="chapter" data-level="4.2.5" data-path="retail.html"><a href="retail.html#customers-behavior-in-each-factor-based-on-their-label"><i class="fa fa-check"></i><b>4.2.5</b> Customer’s behavior in each factor based on their label</a></li>
<li class="chapter" data-level="4.2.6" data-path="retail.html"><a href="retail.html#conclusion-1"><i class="fa fa-check"></i><b>4.2.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="retail.html"><a href="retail.html#feature-recommendation-on-mobile-games"><i class="fa fa-check"></i><b>4.3</b> Feature Recommendation on Mobile Games</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="retail.html"><a href="retail.html#background-5"><i class="fa fa-check"></i><b>4.3.1</b> Background</a></li>
<li class="chapter" data-level="4.3.2" data-path="retail.html"><a href="retail.html#data-preparation"><i class="fa fa-check"></i><b>4.3.2</b> Data Preparation</a></li>
<li class="chapter" data-level="4.3.3" data-path="retail.html"><a href="retail.html#exploratory-data-analysis-2"><i class="fa fa-check"></i><b>4.3.3</b> Exploratory Data Analysis</a></li>
<li class="chapter" data-level="4.3.4" data-path="retail.html"><a href="retail.html#modeling"><i class="fa fa-check"></i><b>4.3.4</b> Modeling</a></li>
<li class="chapter" data-level="4.3.5" data-path="retail.html"><a href="retail.html#conclusion-2"><i class="fa fa-check"></i><b>4.3.5</b> Conclusion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="insurance.html"><a href="insurance.html"><i class="fa fa-check"></i><b>5</b> Insurance</a>
<ul>
<li class="chapter" data-level="5.1" data-path="insurance.html"><a href="insurance.html#prediction-of-total-claim-amount"><i class="fa fa-check"></i><b>5.1</b> Prediction of Total Claim Amount</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="insurance.html"><a href="insurance.html#background-6"><i class="fa fa-check"></i><b>5.1.1</b> Background</a></li>
<li class="chapter" data-level="5.1.2" data-path="insurance.html"><a href="insurance.html#modelling-analysis-3"><i class="fa fa-check"></i><b>5.1.2</b> Modelling Analysis</a></li>
<li class="chapter" data-level="5.1.3" data-path="insurance.html"><a href="insurance.html#conclusion-3"><i class="fa fa-check"></i><b>5.1.3</b> Conclusion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="bioinformatics.html"><a href="bioinformatics.html"><i class="fa fa-check"></i><b>6</b> Bioinformatics</a>
<ul>
<li class="chapter" data-level="6.1" data-path="bioinformatics.html"><a href="bioinformatics.html#qtl-mapping-for-disease-resistance"><i class="fa fa-check"></i><b>6.1</b> QTL Mapping for Disease Resistance</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="bioinformatics.html"><a href="bioinformatics.html#backgorund"><i class="fa fa-check"></i><b>6.1.1</b> Backgorund</a></li>
<li class="chapter" data-level="6.1.2" data-path="bioinformatics.html"><a href="bioinformatics.html#modelling-analysis-4"><i class="fa fa-check"></i><b>6.1.2</b> Modelling Analysis</a></li>
<li class="chapter" data-level="6.1.3" data-path="bioinformatics.html"><a href="bioinformatics.html#conclusion-4"><i class="fa fa-check"></i><b>6.1.3</b> Conclusion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="public-health.html"><a href="public-health.html"><i class="fa fa-check"></i><b>7</b> Public Health</a>
<ul>
<li class="chapter" data-level="7.1" data-path="public-health.html"><a href="public-health.html#survival-analysis-of-patients-with-lung-cancer"><i class="fa fa-check"></i><b>7.1</b> Survival Analysis of Patients with Lung Cancer</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="public-health.html"><a href="public-health.html#import-data-3"><i class="fa fa-check"></i><b>7.1.1</b> Import Data</a></li>
<li class="chapter" data-level="7.1.2" data-path="public-health.html"><a href="public-health.html#exploratory-data-analysis-4"><i class="fa fa-check"></i><b>7.1.2</b> Exploratory Data Analysis</a></li>
<li class="chapter" data-level="7.1.3" data-path="public-health.html"><a href="public-health.html#modelling-analysis-5"><i class="fa fa-check"></i><b>7.1.3</b> Modelling Analysis</a></li>
<li class="chapter" data-level="7.1.4" data-path="public-health.html"><a href="public-health.html#conclusion-5"><i class="fa fa-check"></i><b>7.1.4</b> Conclusion</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="media.html"><a href="media.html"><i class="fa fa-check"></i><b>8</b> Media</a>
<ul>
<li class="chapter" data-level="8.1" data-path="media.html"><a href="media.html#causal-impact-on-leads-generation"><i class="fa fa-check"></i><b>8.1</b> Causal Impact on Leads generation</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="media.html"><a href="media.html#background-7"><i class="fa fa-check"></i><b>8.1.1</b> Background</a></li>
<li class="chapter" data-level="8.1.2" data-path="media.html"><a href="media.html#modelling-analysis-6"><i class="fa fa-check"></i><b>8.1.2</b> Modelling Analysis</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="travel-and-accomodation.html"><a href="travel-and-accomodation.html"><i class="fa fa-check"></i><b>9</b> Travel and Accomodation</a>
<ul>
<li class="chapter" data-level="9.1" data-path="travel-and-accomodation.html"><a href="travel-and-accomodation.html#topic-modelling-and-sentiment-analysis-on-hotel-reviews-data-in-europe"><i class="fa fa-check"></i><b>9.1</b> Topic Modelling and Sentiment Analysis on Hotel Reviews Data in Europe</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="travel-and-accomodation.html"><a href="travel-and-accomodation.html#background-8"><i class="fa fa-check"></i><b>9.1.1</b> Background</a></li>
<li class="chapter" data-level="9.1.2" data-path="travel-and-accomodation.html"><a href="travel-and-accomodation.html#data-preparation-1"><i class="fa fa-check"></i><b>9.1.2</b> Data Preparation</a></li>
<li class="chapter" data-level="9.1.3" data-path="travel-and-accomodation.html"><a href="travel-and-accomodation.html#exploratory-data-analysis-5"><i class="fa fa-check"></i><b>9.1.3</b> Exploratory Data Analysis</a></li>
<li class="chapter" data-level="9.1.4" data-path="travel-and-accomodation.html"><a href="travel-and-accomodation.html#dashboard-ideas"><i class="fa fa-check"></i><b>9.1.4</b> Dashboard Ideas</a></li>
<li class="chapter" data-level="9.1.5" data-path="travel-and-accomodation.html"><a href="travel-and-accomodation.html#conclusion-6"><i class="fa fa-check"></i><b>9.1.5</b> Conclusion</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://algorit.ma/" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Machine Learning Application in Industry</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="travel-and-accomodation" class="section level1" number="9">
<h1><span class="header-section-number">Chapter 9</span> Travel and Accomodation</h1>
<div id="topic-modelling-and-sentiment-analysis-on-hotel-reviews-data-in-europe" class="section level2" number="9.1">
<h2><span class="header-section-number">9.1</span> Topic Modelling and Sentiment Analysis on Hotel Reviews Data in Europe</h2>
<div id="background-8" class="section level3" number="9.1.1">
<h3><span class="header-section-number">9.1.1</span> Background</h3>
<p>Benua Eropa merupakan benua yang menjadi destinasi impian bagi para wisatawan di berbagai belahan dunia. Hal ini karena Benua Eropa memiliki banyak situs wisata yang menarik perhatian akan keunikan dan keindahannya. Tentunya para wisatawan membutuhkan tempat untuk singgah sementara selama menikmati liburan. Untuk meningkatkan kepuasan para wisatawan, dibutuhkan pemilihan hotel yang tepat agar dapat memberikan wisatawan pengalaman beristirahat yang terbaik. Untuk itu, melihat seberapa baik tingkat pelayanan hotel secara teliti tentunya diperlukan. Tingkat pelayanan hotel dapat dilihat salah-satunya melalui <em>rating</em> dari hotel tersebut. Meskipun demikian, <em>rating</em> dari hotel tidak sepenuhnya merepresentasikan tingkat kelayakan dari hotel tersebut, terutama untuk fasilitas-fasilitasnya secara spesifik. Maka dari itu, perlu dilakukan analisis sentimen berdasarkan ulasan dari wisatawan lain yang pernah singgah di hotel tersebut. Sentimen analisis diperlukan untuk memberikan penilaian terhadap fasilitas-fasilitas dan pelayanan hotel yang disediakan karena sering kali kita tidak ingin membaca setiap ulasan hotel-hotel tersebut satu per satu. Harapannya, dengan analisis ini, hasil penilaian dari setiap aspek pelayanan dari hotel-hotel ini dapat dijadikan pertimbangan dalam memilih hotel dengan pengalaman menginap yang terbaik.</p>
</div>
<div id="data-preparation-1" class="section level3" number="9.1.2">
<h3><span class="header-section-number">9.1.2</span> Data Preparation</h3>
<p>Dataset yang digunakan adalah dataset yang bersumber dari kaggle (<a href="https://www.kaggle.com/jiashenliu/515k-hotel-reviews-data-in-europe" class="uri">https://www.kaggle.com/jiashenliu/515k-hotel-reviews-data-in-europe</a>) yang memuat 515 ribu ulasan dari hotel-hotel yang berada di ibukota negara-negara di Benua Eropa.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb1-1"><a href="travel-and-accomodation.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys</span>
<span id="cb1-2"><a href="travel-and-accomodation.html#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(sys.executable)</span></code></pre></div>
<pre><code>#&gt; /Users/ariqleesta/opt/anaconda3/envs/ariq/bin/python</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb3-1"><a href="travel-and-accomodation.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Environment</span></span>
<span id="cb3-2"><a href="travel-and-accomodation.html#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb3-3"><a href="travel-and-accomodation.html#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="travel-and-accomodation.html#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Data Manipulation Tools</span></span>
<span id="cb3-5"><a href="travel-and-accomodation.html#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb3-6"><a href="travel-and-accomodation.html#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb3-7"><a href="travel-and-accomodation.html#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> fuzzymatcher <span class="im">import</span> link_table, fuzzy_left_join</span>
<span id="cb3-8"><a href="travel-and-accomodation.html#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> difflib</span>
<span id="cb3-9"><a href="travel-and-accomodation.html#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> re <span class="co"># for regular expressions</span></span>
<span id="cb3-10"><a href="travel-and-accomodation.html#cb3-10" aria-hidden="true" tabindex="-1"></a>pd.options.display.max_rows <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb3-11"><a href="travel-and-accomodation.html#cb3-11" aria-hidden="true" tabindex="-1"></a>pd.options.display.max_columns <span class="op">=</span> <span class="dv">100</span></span>
<span id="cb3-12"><a href="travel-and-accomodation.html#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="travel-and-accomodation.html#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Data Visualization Tools</span></span>
<span id="cb3-14"><a href="travel-and-accomodation.html#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb3-15"><a href="travel-and-accomodation.html#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb3-16"><a href="travel-and-accomodation.html#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="co">#%matplotlib inline</span></span>
<span id="cb3-17"><a href="travel-and-accomodation.html#cb3-17" aria-hidden="true" tabindex="-1"></a>plt.style.use(<span class="st">&#39;bmh&#39;</span>)</span>
<span id="cb3-18"><a href="travel-and-accomodation.html#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="travel-and-accomodation.html#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="co"># libraries for displaying images</span></span>
<span id="cb3-20"><a href="travel-and-accomodation.html#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> HTML, Image </span>
<span id="cb3-21"><a href="travel-and-accomodation.html#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.core.display <span class="im">import</span> HTML </span>
<span id="cb3-22"><a href="travel-and-accomodation.html#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> display</span>
<span id="cb3-23"><a href="travel-and-accomodation.html#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> selenium</span>
<span id="cb3-24"><a href="travel-and-accomodation.html#cb3-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-25"><a href="travel-and-accomodation.html#cb3-25" aria-hidden="true" tabindex="-1"></a><span class="co"># NLP Module</span></span>
<span id="cb3-26"><a href="travel-and-accomodation.html#cb3-26" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> nltk <span class="co"># Natural language processing toolkit</span></span>
<span id="cb3-27"><a href="travel-and-accomodation.html#cb3-27" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> nltk <span class="im">import</span> FreqDist <span class="co"># Frequency distribution</span></span>
<span id="cb3-28"><a href="travel-and-accomodation.html#cb3-28" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> nltk.corpus <span class="im">import</span> stopwords</span>
<span id="cb3-29"><a href="travel-and-accomodation.html#cb3-29" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> wordcloud <span class="im">import</span> WordCloud,STOPWORDS </span>
<span id="cb3-30"><a href="travel-and-accomodation.html#cb3-30" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> textblob <span class="im">import</span> TextBlob</span>
<span id="cb3-31"><a href="travel-and-accomodation.html#cb3-31" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> nltk.stem <span class="im">import</span> WordNetLemmatizer </span>
<span id="cb3-32"><a href="travel-and-accomodation.html#cb3-32" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> nltk <span class="im">import</span> sent_tokenize</span>
<span id="cb3-33"><a href="travel-and-accomodation.html#cb3-33" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> math <span class="im">import</span> pi</span>
<span id="cb3-34"><a href="travel-and-accomodation.html#cb3-34" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pickle </span>
<span id="cb3-35"><a href="travel-and-accomodation.html#cb3-35" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pyLDAvis</span>
<span id="cb3-36"><a href="travel-and-accomodation.html#cb3-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-37"><a href="travel-and-accomodation.html#cb3-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-38"><a href="travel-and-accomodation.html#cb3-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Network</span></span></code></pre></div>
<pre><code>#&gt; /Library/Frameworks/R.framework/Versions/4.1/Resources/library/reticulate/python/rpytools/loader.py:39: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module&#39;s documentation for alternative uses
#&gt;   module = _import(</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb5-1"><a href="travel-and-accomodation.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> nltk <span class="im">import</span> bigrams, ngrams</span>
<span id="cb5-2"><a href="travel-and-accomodation.html#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> networkx <span class="im">as</span> nx </span>
<span id="cb5-3"><a href="travel-and-accomodation.html#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> itertools</span>
<span id="cb5-4"><a href="travel-and-accomodation.html#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> collections</span>
<span id="cb5-5"><a href="travel-and-accomodation.html#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="travel-and-accomodation.html#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Location Modules</span></span>
<span id="cb5-7"><a href="travel-and-accomodation.html#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> folium</span>
<span id="cb5-8"><a href="travel-and-accomodation.html#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="travel-and-accomodation.html#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Ignore Warnings</span></span>
<span id="cb5-10"><a href="travel-and-accomodation.html#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb5-11"><a href="travel-and-accomodation.html#cb5-11" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">&quot;ignore&quot;</span>)</span>
<span id="cb5-12"><a href="travel-and-accomodation.html#cb5-12" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">&quot;ignore&quot;</span>, category<span class="op">=</span> <span class="pp">DeprecationWarning</span>)</span></code></pre></div>
<div class="sourceCode" id="cb6"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb6-1"><a href="travel-and-accomodation.html#cb6-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">&#39;https://archive.org/download/hotel-reviews/Hotel_Reviews.csv&#39;</span>)</span>
<span id="cb6-2"><a href="travel-and-accomodation.html#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.shape)</span></code></pre></div>
<pre><code>#&gt; (515738, 17)</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb8-1"><a href="travel-and-accomodation.html#cb8-1" aria-hidden="true" tabindex="-1"></a>df.head(<span class="dv">2</span>)</span></code></pre></div>
<pre><code>#&gt;                                        Hotel_Address  \
#&gt; 0   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...   
#&gt; 1   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...   
#&gt; 
#&gt;    Additional_Number_of_Scoring Review_Date  Average_Score   Hotel_Name  \
#&gt; 0                           194    8/3/2017            7.7  Hotel Arena   
#&gt; 1                           194    8/3/2017            7.7  Hotel Arena   
#&gt; 
#&gt;   Reviewer_Nationality                                    Negative_Review  \
#&gt; 0              Russia    I am so angry that i made this post available...   
#&gt; 1             Ireland                                         No Negative   
#&gt; 
#&gt;    Review_Total_Negative_Word_Counts  Total_Number_of_Reviews  \
#&gt; 0                                397                     1403   
#&gt; 1                                  0                     1403   
#&gt; 
#&gt;                                      Positive_Review  \
#&gt; 0   Only the park outside of the hotel was beauti...   
#&gt; 1   No real complaints the hotel was great great ...   
#&gt; 
#&gt;    Review_Total_Positive_Word_Counts  \
#&gt; 0                                 11   
#&gt; 1                                105   
#&gt; 
#&gt;    Total_Number_of_Reviews_Reviewer_Has_Given  Reviewer_Score  \
#&gt; 0                                           7             2.9   
#&gt; 1                                           7             7.5   
#&gt; 
#&gt;                                                 Tags days_since_review  \
#&gt; 0  [&#39; Leisure trip &#39;, &#39; Couple &#39;, &#39; Duplex Double...            0 days   
#&gt; 1  [&#39; Leisure trip &#39;, &#39; Couple &#39;, &#39; Duplex Double...            0 days   
#&gt; 
#&gt;          lat       lng  
#&gt; 0  52.360576  4.915968  
#&gt; 1  52.360576  4.915968</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb10-1"><a href="travel-and-accomodation.html#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="bu">len</span>(df[<span class="st">&#39;Hotel_Address&#39;</span>].unique())</span></code></pre></div>
<pre><code>#&gt; 1493</code></pre>
<p>Dataset ini memiliki 515738 baris dan 17 kolom dengan jumlah hotel sebanyak 1493. Sebelum memulai analisis lebih lanjut, kita perlu mengetahui tipe data dari setiap kolom dataset tersebut.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb12-1"><a href="travel-and-accomodation.html#cb12-1" aria-hidden="true" tabindex="-1"></a>df.dtypes</span></code></pre></div>
<pre><code>#&gt; Hotel_Address                                  object
#&gt; Additional_Number_of_Scoring                    int64
#&gt; Review_Date                                    object
#&gt; Average_Score                                 float64
#&gt; Hotel_Name                                     object
#&gt; Reviewer_Nationality                           object
#&gt; Negative_Review                                object
#&gt; Review_Total_Negative_Word_Counts               int64
#&gt; Total_Number_of_Reviews                         int64
#&gt; Positive_Review                                object
#&gt; Review_Total_Positive_Word_Counts               int64
#&gt; Total_Number_of_Reviews_Reviewer_Has_Given      int64
#&gt; Reviewer_Score                                float64
#&gt; Tags                                           object
#&gt; days_since_review                              object
#&gt; lat                                           float64
#&gt; lng                                           float64
#&gt; dtype: object</code></pre>
<p>Kemudian kita perlu meninjau mengenai <em>missing value</em> atau data yang hilang dari dataset tersebut. Pengamatan data yang hilang dapat dilakukan secara visual dengan bantuan <em>library</em> missingno.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb14-1"><a href="travel-and-accomodation.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> missingno <span class="im">as</span> msno</span>
<span id="cb14-2"><a href="travel-and-accomodation.html#cb14-2" aria-hidden="true" tabindex="-1"></a>plt.figure()</span></code></pre></div>

<div class="sourceCode" id="cb15"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb15-1"><a href="travel-and-accomodation.html#cb15-1" aria-hidden="true" tabindex="-1"></a>msno.matrix(df, figsize <span class="op">=</span> (<span class="dv">20</span>,<span class="dv">8</span>))</span></code></pre></div>
<pre><code>#&gt; &lt;AxesSubplot:&gt;</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb17-1"><a href="travel-and-accomodation.html#cb17-1" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div>
<p><img src="bookmlindustry_files/figure-html/unnamed-chunk-3-1.png" width="1920" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb18"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb18-1"><a href="travel-and-accomodation.html#cb18-1" aria-hidden="true" tabindex="-1"></a>df.isnull().<span class="bu">sum</span>()</span></code></pre></div>
<pre><code>#&gt; Hotel_Address                                    0
#&gt; Additional_Number_of_Scoring                     0
#&gt; Review_Date                                      0
#&gt; Average_Score                                    0
#&gt; Hotel_Name                                       0
#&gt; Reviewer_Nationality                             0
#&gt; Negative_Review                                  0
#&gt; Review_Total_Negative_Word_Counts                0
#&gt; Total_Number_of_Reviews                          0
#&gt; Positive_Review                                  0
#&gt; Review_Total_Positive_Word_Counts                0
#&gt; Total_Number_of_Reviews_Reviewer_Has_Given       0
#&gt; Reviewer_Score                                   0
#&gt; Tags                                             0
#&gt; days_since_review                                0
#&gt; lat                                           3268
#&gt; lng                                           3268
#&gt; dtype: int64</code></pre>
<p>Kolom <em>lat</em> dan <em>lng</em> yang merupakan komponen koordinat dari dataset tidak tersedia untuk beberapa hotel. Jumlah baris yang tidak memiliki data koordinat sangat sedikit jika dibandingkan total data keseluruhan sehingga baris-baris ini dapat dihilangkan karena koordinat diperlukan untuk memberikan informasi lokasi dari hotel tersebut kepada para wisatawan.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb20-1"><a href="travel-and-accomodation.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># drop null coordinates</span></span>
<span id="cb20-2"><a href="travel-and-accomodation.html#cb20-2" aria-hidden="true" tabindex="-1"></a>df.dropna(inplace <span class="op">=</span> <span class="va">True</span>)</span></code></pre></div>
</div>
<div id="exploratory-data-analysis-5" class="section level3" number="9.1.3">
<h3><span class="header-section-number">9.1.3</span> Exploratory Data Analysis</h3>
<p>Kata <em>No Negative</em> pada kolom <em>Negative Review</em> dan <em>No Positive</em> pada kolom <em>Positive Review</em> menandakan bahwa review tersebut tidak mengandung ulasan positif atau ulasan negatif. Sehingga kata <em>No Negative</em> dan <em>No Positive</em> dapat diganti dengan <em>empty string</em> saja.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb21-1"><a href="travel-and-accomodation.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># replace No Negative and No Positive with empty string</span></span>
<span id="cb21-2"><a href="travel-and-accomodation.html#cb21-2" aria-hidden="true" tabindex="-1"></a>df[<span class="st">&#39;Negative_Review&#39;</span>] <span class="op">=</span> df[<span class="st">&#39;Negative_Review&#39;</span>].replace({<span class="st">&#39;No Negative&#39;</span>: <span class="st">&#39;&#39;</span>})</span>
<span id="cb21-3"><a href="travel-and-accomodation.html#cb21-3" aria-hidden="true" tabindex="-1"></a>df[<span class="st">&#39;Positive_Review&#39;</span>] <span class="op">=</span> df[<span class="st">&#39;Positive_Review&#39;</span>].replace({<span class="st">&#39;No Positive&#39;</span>: <span class="st">&#39;&#39;</span>})</span></code></pre></div>
<p>Berikut adalah distribusi dari nilai <em>rating</em> rata-rata yang diberikan oleh pemberi ulasan terkait hotel-hotel pada dataset ini. <em>Average Score</em> memiliki rentang 5.2 untuk nilai terendah dan 9.9 untuk nilai tertinggi.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb22-1"><a href="travel-and-accomodation.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot average score</span></span>
<span id="cb22-2"><a href="travel-and-accomodation.html#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="travel-and-accomodation.html#cb22-3" aria-hidden="true" tabindex="-1"></a>data_plot <span class="op">=</span> df[[<span class="st">&quot;Hotel_Name&quot;</span>,<span class="st">&quot;Average_Score&quot;</span>]].drop_duplicates()</span>
<span id="cb22-4"><a href="travel-and-accomodation.html#cb22-4" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span> (<span class="dv">30</span>,<span class="dv">7</span>))</span>
<span id="cb22-5"><a href="travel-and-accomodation.html#cb22-5" aria-hidden="true" tabindex="-1"></a>sns.countplot(ax <span class="op">=</span> ax,x <span class="op">=</span> <span class="st">&quot;Average_Score&quot;</span>,data<span class="op">=</span>data_plot)</span></code></pre></div>
<pre><code>#&gt; &lt;AxesSubplot:xlabel=&#39;Average_Score&#39;, ylabel=&#39;count&#39;&gt;</code></pre>
<div class="sourceCode" id="cb24"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb24-1"><a href="travel-and-accomodation.html#cb24-1" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">&#39;Average Score&#39;</span>)</span></code></pre></div>
<pre><code>#&gt; Text(0.5, 0, &#39;Average Score&#39;)</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb26-1"><a href="travel-and-accomodation.html#cb26-1" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">&#39;Score Counts&#39;</span>)</span></code></pre></div>
<pre><code>#&gt; Text(0, 0.5, &#39;Score Counts&#39;)</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb28-1"><a href="travel-and-accomodation.html#cb28-1" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div>
<p><img src="bookmlindustry_files/figure-html/unnamed-chunk-3-3.png" width="2880" style="display: block; margin: auto;" /></p>
<p>Berikut akan dilakukan analisis teks, tahap-tahap yang akan dilakukan antara lain:
* Mendefinisikan <em>Stopword</em> <br>
<em>Stopword</em> adalah kata-kata yang tidak atau sedikit mengandung makna dari kalimat keseluruhan. <em>Stopword</em> biasanya berupa partikel (<em>eg: a, an, the, is, am, are</em>) atau kata penghubung (<em>eg: and, or, of</em>).
* Membuat semua kata menjadi huruf kecil/<em>lowercase</em> <br>
Untuk mempermudah memproses data tekstual, perlu dilakukan <em>lowercasing</em> karena algoritma dalam text processing membedakan huruf besar dan huruf kecil atau <em>case sensitive</em>.
* Menghilangkan <em>character</em> yang tidak diinginkan <br>
<em>Character</em> yang tidak diinginkan bisa berupa simbol simbol seperti titik, koma, tanda seru, tanda tanya, dan lain-lain.
* Menghilangkan kata-kata yang pendek (kurang dari 4 huruf)
* <em>Lemmatizing</em> <br>
<em>Lemmatizing</em> adalah mengembalikan kosa kata menjadi kata dasar dari kata tersebut. Sebagai contoh,, kata <em>studying</em> dan <em>studied</em> memiliki kata dasar yang sama yaitu <em>study</em>.
* Menghilangkan <em>Stopwords</em></p>
<ul>
<li><em>Tokenization</em>
<em>Tokenization</em> adalah proses memecah kalimat menjadi kumpulan kata-kata. Kumpulan kata-kata dalam satu kalimat dimuat dalam satu buah <em>iterable</em> atau <em>list</em>. Sebagai contoh, untuk kata yang telah di <em>lemmatizing</em>, “<em>Hotel service good</em>” menjadi [“Hotel,” “Service,” “Good”].</li>
</ul>
<div class="sourceCode" id="cb29"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb29-1"><a href="travel-and-accomodation.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A function to remove stopwords</span></span>
<span id="cb29-2"><a href="travel-and-accomodation.html#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> remove_stopwords(rev):</span>
<span id="cb29-3"><a href="travel-and-accomodation.html#cb29-3" aria-hidden="true" tabindex="-1"></a>    rev_new <span class="op">=</span> <span class="st">&quot; &quot;</span>.join([i <span class="cf">for</span> i <span class="kw">in</span> rev <span class="cf">if</span> i <span class="kw">not</span> <span class="kw">in</span> stop_words])</span>
<span id="cb29-4"><a href="travel-and-accomodation.html#cb29-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> rev_new</span>
<span id="cb29-5"><a href="travel-and-accomodation.html#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="travel-and-accomodation.html#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="co"># A function to count the most frequent words</span></span>
<span id="cb29-7"><a href="travel-and-accomodation.html#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> freq_words(x, terms <span class="op">=</span> <span class="dv">30</span>):</span>
<span id="cb29-8"><a href="travel-and-accomodation.html#cb29-8" aria-hidden="true" tabindex="-1"></a>    all_words <span class="op">=</span> <span class="st">&#39; &#39;</span>.join([text <span class="cf">for</span> text <span class="kw">in</span> x])</span>
<span id="cb29-9"><a href="travel-and-accomodation.html#cb29-9" aria-hidden="true" tabindex="-1"></a>    all_words <span class="op">=</span> all_words.split()</span>
<span id="cb29-10"><a href="travel-and-accomodation.html#cb29-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-11"><a href="travel-and-accomodation.html#cb29-11" aria-hidden="true" tabindex="-1"></a>    fdist <span class="op">=</span> FreqDist(all_words)</span>
<span id="cb29-12"><a href="travel-and-accomodation.html#cb29-12" aria-hidden="true" tabindex="-1"></a>    words_df <span class="op">=</span> pd.DataFrame({<span class="st">&#39;word&#39;</span>:<span class="bu">list</span>(fdist.keys()), <span class="st">&#39;count&#39;</span>:<span class="bu">list</span>(fdist.values())})</span>
<span id="cb29-13"><a href="travel-and-accomodation.html#cb29-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-14"><a href="travel-and-accomodation.html#cb29-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># selecting top 20 most frequent words</span></span>
<span id="cb29-15"><a href="travel-and-accomodation.html#cb29-15" aria-hidden="true" tabindex="-1"></a>    d <span class="op">=</span> words_df.nlargest(columns<span class="op">=</span><span class="st">&quot;count&quot;</span>, n <span class="op">=</span> terms) </span>
<span id="cb29-16"><a href="travel-and-accomodation.html#cb29-16" aria-hidden="true" tabindex="-1"></a>    plt.figure(<span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">20</span>,<span class="dv">5</span>))</span>
<span id="cb29-17"><a href="travel-and-accomodation.html#cb29-17" aria-hidden="true" tabindex="-1"></a>    ax <span class="op">=</span> sns.barplot(data<span class="op">=</span>d, x<span class="op">=</span> <span class="st">&quot;word&quot;</span>, y <span class="op">=</span> <span class="st">&quot;count&quot;</span>)</span>
<span id="cb29-18"><a href="travel-and-accomodation.html#cb29-18" aria-hidden="true" tabindex="-1"></a>    ax.<span class="bu">set</span>(ylabel <span class="op">=</span> <span class="st">&#39;Count&#39;</span>)</span>
<span id="cb29-19"><a href="travel-and-accomodation.html#cb29-19" aria-hidden="true" tabindex="-1"></a>    plt.xticks(rotation <span class="op">=</span> <span class="dv">90</span>)</span>
<span id="cb29-20"><a href="travel-and-accomodation.html#cb29-20" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb29-21"><a href="travel-and-accomodation.html#cb29-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-22"><a href="travel-and-accomodation.html#cb29-22" aria-hidden="true" tabindex="-1"></a><span class="co"># A function to draw word cloud</span></span>
<span id="cb29-23"><a href="travel-and-accomodation.html#cb29-23" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> wordcloud_draw(data, color <span class="op">=</span> <span class="st">&#39;black&#39;</span>):</span>
<span id="cb29-24"><a href="travel-and-accomodation.html#cb29-24" aria-hidden="true" tabindex="-1"></a>    words <span class="op">=</span> <span class="st">&#39; &#39;</span>.join(data)</span>
<span id="cb29-25"><a href="travel-and-accomodation.html#cb29-25" aria-hidden="true" tabindex="-1"></a>    cleaned_word <span class="op">=</span> <span class="st">&#39; &#39;</span>.join([word <span class="cf">for</span> word <span class="kw">in</span> words.split()</span>
<span id="cb29-26"><a href="travel-and-accomodation.html#cb29-26" aria-hidden="true" tabindex="-1"></a>                            <span class="cf">if</span> <span class="st">&#39;http&#39;</span> <span class="kw">not</span> <span class="kw">in</span> word</span>
<span id="cb29-27"><a href="travel-and-accomodation.html#cb29-27" aria-hidden="true" tabindex="-1"></a>                                <span class="kw">and</span> <span class="kw">not</span> word.startswith(<span class="st">&#39;@&#39;</span>)</span>
<span id="cb29-28"><a href="travel-and-accomodation.html#cb29-28" aria-hidden="true" tabindex="-1"></a>                                <span class="kw">and</span> <span class="kw">not</span> word.startswith(<span class="st">&#39;#&#39;</span>)</span>
<span id="cb29-29"><a href="travel-and-accomodation.html#cb29-29" aria-hidden="true" tabindex="-1"></a>                                <span class="kw">and</span> word <span class="op">!=</span> <span class="st">&#39;RT&#39;</span></span>
<span id="cb29-30"><a href="travel-and-accomodation.html#cb29-30" aria-hidden="true" tabindex="-1"></a>                            ])</span>
<span id="cb29-31"><a href="travel-and-accomodation.html#cb29-31" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb29-32"><a href="travel-and-accomodation.html#cb29-32" aria-hidden="true" tabindex="-1"></a>    wordcloud <span class="op">=</span> WordCloud(collocations<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb29-33"><a href="travel-and-accomodation.html#cb29-33" aria-hidden="true" tabindex="-1"></a>              stopwords<span class="op">=</span>STOPWORDS,</span>
<span id="cb29-34"><a href="travel-and-accomodation.html#cb29-34" aria-hidden="true" tabindex="-1"></a>              background_color<span class="op">=</span>color,</span>
<span id="cb29-35"><a href="travel-and-accomodation.html#cb29-35" aria-hidden="true" tabindex="-1"></a>              width<span class="op">=</span><span class="dv">500</span>,</span>
<span id="cb29-36"><a href="travel-and-accomodation.html#cb29-36" aria-hidden="true" tabindex="-1"></a>              height<span class="op">=</span><span class="dv">100</span>,).generate(cleaned_word)</span>
<span id="cb29-37"><a href="travel-and-accomodation.html#cb29-37" aria-hidden="true" tabindex="-1"></a>    plt.figure(<span class="dv">1</span>,figsize<span class="op">=</span>(<span class="dv">13</span>, <span class="dv">13</span>))</span>
<span id="cb29-38"><a href="travel-and-accomodation.html#cb29-38" aria-hidden="true" tabindex="-1"></a>    plt.imshow(wordcloud)</span>
<span id="cb29-39"><a href="travel-and-accomodation.html#cb29-39" aria-hidden="true" tabindex="-1"></a>    plt.axis(<span class="st">&#39;off&#39;</span>)</span>
<span id="cb29-40"><a href="travel-and-accomodation.html#cb29-40" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb29-41"><a href="travel-and-accomodation.html#cb29-41" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb29-42"><a href="travel-and-accomodation.html#cb29-42" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a function to get the subjectivity</span></span>
<span id="cb29-43"><a href="travel-and-accomodation.html#cb29-43" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> getSubjectivity(text):</span>
<span id="cb29-44"><a href="travel-and-accomodation.html#cb29-44" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> TextBlob(text).sentiment.subjectivity</span>
<span id="cb29-45"><a href="travel-and-accomodation.html#cb29-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-46"><a href="travel-and-accomodation.html#cb29-46" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a function to get the polarity</span></span>
<span id="cb29-47"><a href="travel-and-accomodation.html#cb29-47" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> getPolarity(text):</span>
<span id="cb29-48"><a href="travel-and-accomodation.html#cb29-48" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> TextBlob(text).sentiment.polarity</span></code></pre></div>
<div class="sourceCode" id="cb30"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb30-1"><a href="travel-and-accomodation.html#cb30-1" aria-hidden="true" tabindex="-1"></a>df_reviews <span class="op">=</span> df[[<span class="st">&#39;Hotel_Name&#39;</span>, <span class="st">&#39;Negative_Review&#39;</span>, <span class="st">&#39;Positive_Review&#39;</span>]]</span>
<span id="cb30-2"><a href="travel-and-accomodation.html#cb30-2" aria-hidden="true" tabindex="-1"></a>df_reviews.head()</span>
<span id="cb30-3"><a href="travel-and-accomodation.html#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="travel-and-accomodation.html#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Define stopwords</span></span></code></pre></div>
<pre><code>#&gt;     Hotel_Name                                    Negative_Review  \
#&gt; 0  Hotel Arena   I am so angry that i made this post available...   
#&gt; 1  Hotel Arena                                                      
#&gt; 2  Hotel Arena   Rooms are nice but for elderly a bit difficul...   
#&gt; 3  Hotel Arena   My room was dirty and I was afraid to walk ba...   
#&gt; 4  Hotel Arena   You When I booked with your company on line y...   
#&gt; 
#&gt;                                      Positive_Review  
#&gt; 0   Only the park outside of the hotel was beauti...  
#&gt; 1   No real complaints the hotel was great great ...  
#&gt; 2   Location was good and staff were ok It is cut...  
#&gt; 3   Great location in nice surroundings the bar a...  
#&gt; 4    Amazing location and building Romantic setting</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb32-1"><a href="travel-and-accomodation.html#cb32-1" aria-hidden="true" tabindex="-1"></a>stop_words <span class="op">=</span> stopwords.words(<span class="st">&#39;english&#39;</span>)</span>
<span id="cb32-2"><a href="travel-and-accomodation.html#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="travel-and-accomodation.html#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="co"># make entire text lowercase</span></span>
<span id="cb32-4"><a href="travel-and-accomodation.html#cb32-4" aria-hidden="true" tabindex="-1"></a>df_reviews[<span class="st">&#39;Positive_Review&#39;</span>] <span class="op">=</span> [r.lower() <span class="cf">for</span> r <span class="kw">in</span> df_reviews[<span class="st">&#39;Positive_Review&#39;</span>]] </span>
<span id="cb32-5"><a href="travel-and-accomodation.html#cb32-5" aria-hidden="true" tabindex="-1"></a>df_reviews[<span class="st">&#39;Negative_Review&#39;</span>] <span class="op">=</span> [r.lower() <span class="cf">for</span> r <span class="kw">in</span> df_reviews[<span class="st">&#39;Negative_Review&#39;</span>]]</span>
<span id="cb32-6"><a href="travel-and-accomodation.html#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="travel-and-accomodation.html#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove unwanted characters, numbers and symbols</span></span>
<span id="cb32-8"><a href="travel-and-accomodation.html#cb32-8" aria-hidden="true" tabindex="-1"></a>df_reviews[<span class="st">&#39;Positive_Review&#39;</span>] <span class="op">=</span> df_reviews[<span class="st">&#39;Positive_Review&#39;</span>].<span class="bu">str</span>.replace(<span class="st">&quot;[^a-zA-Z#]&quot;</span>, <span class="st">&quot; &quot;</span>)</span>
<span id="cb32-9"><a href="travel-and-accomodation.html#cb32-9" aria-hidden="true" tabindex="-1"></a>df_reviews[<span class="st">&#39;Negative_Review&#39;</span>] <span class="op">=</span> df_reviews[<span class="st">&#39;Negative_Review&#39;</span>].<span class="bu">str</span>.replace(<span class="st">&quot;[^a-zA-Z#]&quot;</span>, <span class="st">&quot; &quot;</span>)</span>
<span id="cb32-10"><a href="travel-and-accomodation.html#cb32-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-11"><a href="travel-and-accomodation.html#cb32-11" aria-hidden="true" tabindex="-1"></a><span class="co"># remove short words (length &lt; 4)</span></span>
<span id="cb32-12"><a href="travel-and-accomodation.html#cb32-12" aria-hidden="true" tabindex="-1"></a>df_reviews[<span class="st">&#39;Positive_Review&#39;</span>] <span class="op">=</span> df_reviews[<span class="st">&#39;Positive_Review&#39;</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="st">&#39; &#39;</span>.join([w <span class="cf">for</span> w <span class="kw">in</span> x.split() <span class="cf">if</span> <span class="bu">len</span>(w)<span class="op">&gt;</span><span class="dv">3</span>]))</span>
<span id="cb32-13"><a href="travel-and-accomodation.html#cb32-13" aria-hidden="true" tabindex="-1"></a>df_reviews[<span class="st">&#39;Negative_Review&#39;</span>] <span class="op">=</span> df_reviews[<span class="st">&#39;Negative_Review&#39;</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: <span class="st">&#39; &#39;</span>.join([w <span class="cf">for</span> w <span class="kw">in</span> x.split() <span class="cf">if</span> <span class="bu">len</span>(w)<span class="op">&gt;</span><span class="dv">3</span>]))</span>
<span id="cb32-14"><a href="travel-and-accomodation.html#cb32-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-15"><a href="travel-and-accomodation.html#cb32-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Lemmatizing </span></span>
<span id="cb32-16"><a href="travel-and-accomodation.html#cb32-16" aria-hidden="true" tabindex="-1"></a>lemmatizer <span class="op">=</span> WordNetLemmatizer() </span>
<span id="cb32-17"><a href="travel-and-accomodation.html#cb32-17" aria-hidden="true" tabindex="-1"></a>df_reviews[<span class="st">&#39;Positive_Review&#39;</span>] <span class="op">=</span> [<span class="st">&#39; &#39;</span>.join([lemmatizer.lemmatize(word) <span class="cf">for</span> word <span class="kw">in</span> r.split(<span class="st">&#39; &#39;</span>)]) <span class="cf">for</span> r <span class="kw">in</span> df_reviews[<span class="st">&#39;Positive_Review&#39;</span>]]</span>
<span id="cb32-18"><a href="travel-and-accomodation.html#cb32-18" aria-hidden="true" tabindex="-1"></a>df_reviews[<span class="st">&#39;Negative_Review&#39;</span>] <span class="op">=</span> [<span class="st">&#39; &#39;</span>.join([lemmatizer.lemmatize(word) <span class="cf">for</span> word <span class="kw">in</span> r.split(<span class="st">&#39; &#39;</span>)]) <span class="cf">for</span> r <span class="kw">in</span> df_reviews[<span class="st">&#39;Negative_Review&#39;</span>]]</span>
<span id="cb32-19"><a href="travel-and-accomodation.html#cb32-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-20"><a href="travel-and-accomodation.html#cb32-20" aria-hidden="true" tabindex="-1"></a><span class="co"># remove stopwords from the text</span></span>
<span id="cb32-21"><a href="travel-and-accomodation.html#cb32-21" aria-hidden="true" tabindex="-1"></a>df_reviews[<span class="st">&#39;Positive_Review&#39;</span>] <span class="op">=</span> [remove_stopwords(r.split()) <span class="cf">for</span> r <span class="kw">in</span> df_reviews[<span class="st">&#39;Positive_Review&#39;</span>]]</span>
<span id="cb32-22"><a href="travel-and-accomodation.html#cb32-22" aria-hidden="true" tabindex="-1"></a>df_reviews[<span class="st">&#39;Negative_Review&#39;</span>] <span class="op">=</span> [remove_stopwords(r.split()) <span class="cf">for</span> r <span class="kw">in</span> df_reviews[<span class="st">&#39;Negative_Review&#39;</span>]]</span>
<span id="cb32-23"><a href="travel-and-accomodation.html#cb32-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-24"><a href="travel-and-accomodation.html#cb32-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-25"><a href="travel-and-accomodation.html#cb32-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Tokenization</span></span>
<span id="cb32-26"><a href="travel-and-accomodation.html#cb32-26" aria-hidden="true" tabindex="-1"></a>df_reviews[<span class="st">&#39;Positive_Review&#39;</span>] <span class="op">=</span> [r.split() <span class="cf">for</span> r <span class="kw">in</span> df_reviews[<span class="st">&#39;Positive_Review&#39;</span>]]</span>
<span id="cb32-27"><a href="travel-and-accomodation.html#cb32-27" aria-hidden="true" tabindex="-1"></a>df_reviews[<span class="st">&#39;Negative_Review&#39;</span>] <span class="op">=</span> [r.split() <span class="cf">for</span> r <span class="kw">in</span> df_reviews[<span class="st">&#39;Negative_Review&#39;</span>]]</span></code></pre></div>
<div class="sourceCode" id="cb33"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb33-1"><a href="travel-and-accomodation.html#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> flatten(data):</span>
<span id="cb33-2"><a href="travel-and-accomodation.html#cb33-2" aria-hidden="true" tabindex="-1"></a>    l <span class="op">=</span> []</span>
<span id="cb33-3"><a href="travel-and-accomodation.html#cb33-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> data:</span>
<span id="cb33-4"><a href="travel-and-accomodation.html#cb33-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> word <span class="kw">in</span> i:</span>
<span id="cb33-5"><a href="travel-and-accomodation.html#cb33-5" aria-hidden="true" tabindex="-1"></a>            l.append(word)</span>
<span id="cb33-6"><a href="travel-and-accomodation.html#cb33-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> l</span>
<span id="cb33-7"><a href="travel-and-accomodation.html#cb33-7" aria-hidden="true" tabindex="-1"></a>pos <span class="op">=</span> flatten(df_reviews[<span class="st">&#39;Positive_Review&#39;</span>].tolist())       </span>
<span id="cb33-8"><a href="travel-and-accomodation.html#cb33-8" aria-hidden="true" tabindex="-1"></a>neg <span class="op">=</span> flatten(df_reviews[<span class="st">&#39;Negative_Review&#39;</span>].tolist())  </span></code></pre></div>
<p>Berikut adalah grafik frekuensi tertinggi untuk kata-kata yang berada pada kolom <em>Positive Review</em> dan <em>Negative Review</em>. Pada kolom <em>Positive Review</em>, kata yang paling banyak diucapkan adalah <em>staff</em>, <em>location</em>, dan <em>room</em>, sedangkan Pada kolom <em>Negative Review</em>, kata yang paling banyak diucapkan adalah <em>room</em>, <em>hotel</em>, dan <em>breakfast</em>.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb34-1"><a href="travel-and-accomodation.html#cb34-1" aria-hidden="true" tabindex="-1"></a>freq_words(pos, <span class="dv">30</span>)<span class="co"># Frequency distribution of common words in positive reviews</span></span></code></pre></div>
<p><img src="bookmlindustry_files/figure-html/unnamed-chunk-3-5.png" width="672" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb35"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb35-1"><a href="travel-and-accomodation.html#cb35-1" aria-hidden="true" tabindex="-1"></a>freq_words(neg, <span class="dv">30</span>) <span class="co"># Checking frequency of most used words in negative reviews</span></span></code></pre></div>
<p><img src="bookmlindustry_files/figure-html/unnamed-chunk-3-7.png" width="672" style="display: block; margin: auto;" /></p>
<p>Kita dapat melihat kata-kata yang sering muncul dengan bantuan visualisasi <em>wordcloud</em>. Kata yang lebih sering muncul akan berukuran lebih besar daripada yang lain.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb36-1"><a href="travel-and-accomodation.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Using wordcloud to visually represent the text data</span></span>
<span id="cb36-2"><a href="travel-and-accomodation.html#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;Positive reviews&quot;</span>)</span></code></pre></div>
<pre><code>#&gt; Positive reviews</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb38-1"><a href="travel-and-accomodation.html#cb38-1" aria-hidden="true" tabindex="-1"></a>wordcloud_draw(pos,<span class="st">&#39;white&#39;</span>)</span></code></pre></div>
<p><img src="bookmlindustry_files/figure-html/unnamed-chunk-3-9.png" width="672" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb39"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb39-1"><a href="travel-and-accomodation.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Using wordcloud to visually represent the text data</span></span>
<span id="cb39-2"><a href="travel-and-accomodation.html#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">&quot;Negative reviews&quot;</span>)</span></code></pre></div>
<pre><code>#&gt; Negative reviews</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb41-1"><a href="travel-and-accomodation.html#cb41-1" aria-hidden="true" tabindex="-1"></a>wordcloud_draw(neg)</span></code></pre></div>
<p><img src="bookmlindustry_files/figure-html/unnamed-chunk-3-11.png" width="672" style="display: block; margin: auto;" />
### Modelling</p>
<p>Dalam menyarankan para wisatawan mengenai hotel dengan pelayanan terbaik, kita perlu meninjau terlebih dahulu aspek-aspek apa yang relevan dalam ulasan-ulasan tersebut sebelum bisa dilanjutkan ke penilaian. Aspek-aspek ini dapat berupa fasilitas-fasilitas atau pelayanan yang diberikan oleh hotel tersebut tergantung seberapa banyak dan relevan hal tersebut dibicarakan di dalam ulasan. Sebagai contoh, anggaplah kita tidak mengetahui fasilitas-fasilitas apa yang diberikan hotel. Dari review tersebut ada yang membicarakan mengenai kamar, kolam renang, kafe, <em>rollercoaster</em> bahkan kebun binatang. Bagaimana kita tahu bahwa topik yang relevan adalah kamar, kolam renang, dan kafe? Bisa saja suatu hotel memiliki <em>rollercoaster</em> atau berada di dekat kebun binatang. Untuk menentukan topik-topik yang relevan dalam penilaian, dibutuhkan suatu proses bernama <em>Topic Modelling</em>. <em>Topic Modelling</em> menilai seberapa relevan suatu kata terhadap kalimat yang membawa pengaruh terbesar dalam pemaknaan suatu kalimat. Salah satu metode dalam <em>Topic Modelling</em> dan yang akan digunakan dalam analisis ini adalah metode <em>Latent Dirichlet Allocation (LDA)</em>. LDA memodelkan topik berdasarkan probabilitas dengan mengasumsikan setiap topik merupakan gabungan dari beberapa pasangan kata, dan setiap dokumen merupakan gabungan dari beberapa topik.</p>
<p>Untuk melakukan <em>Topic Modelling</em> dengan metode LDA dapat dilakukan dengan bantuan suatu <em>library</em> bernama gensim.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb42-1"><a href="travel-and-accomodation.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> gensim</span>
<span id="cb42-2"><a href="travel-and-accomodation.html#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> gensim.utils <span class="im">import</span> simple_preprocess</span>
<span id="cb42-3"><a href="travel-and-accomodation.html#cb42-3" aria-hidden="true" tabindex="-1"></a>LDA <span class="op">=</span> gensim.models.ldamodel.LdaModel</span></code></pre></div>
<div class="sourceCode" id="cb43"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb43-1"><a href="travel-and-accomodation.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> gensim.corpora <span class="im">as</span> corpora</span>
<span id="cb43-2"><a href="travel-and-accomodation.html#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Create Dictionary</span></span>
<span id="cb43-3"><a href="travel-and-accomodation.html#cb43-3" aria-hidden="true" tabindex="-1"></a>id2word_pos <span class="op">=</span> corpora.Dictionary(df_reviews[<span class="st">&#39;Positive_Review&#39;</span>])</span>
<span id="cb43-4"><a href="travel-and-accomodation.html#cb43-4" aria-hidden="true" tabindex="-1"></a>id2word_neg <span class="op">=</span> corpora.Dictionary(df_reviews[<span class="st">&#39;Negative_Review&#39;</span>])</span>
<span id="cb43-5"><a href="travel-and-accomodation.html#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Create Corpus</span></span>
<span id="cb43-6"><a href="travel-and-accomodation.html#cb43-6" aria-hidden="true" tabindex="-1"></a>texts_pos <span class="op">=</span> df_reviews[<span class="st">&#39;Positive_Review&#39;</span>]</span>
<span id="cb43-7"><a href="travel-and-accomodation.html#cb43-7" aria-hidden="true" tabindex="-1"></a>texts_neg <span class="op">=</span> df_reviews[<span class="st">&#39;Negative_Review&#39;</span>]</span>
<span id="cb43-8"><a href="travel-and-accomodation.html#cb43-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Term Document Frequency</span></span>
<span id="cb43-9"><a href="travel-and-accomodation.html#cb43-9" aria-hidden="true" tabindex="-1"></a>corpus_pos <span class="op">=</span> [id2word_pos.doc2bow(text) <span class="cf">for</span> text <span class="kw">in</span> texts_pos]</span>
<span id="cb43-10"><a href="travel-and-accomodation.html#cb43-10" aria-hidden="true" tabindex="-1"></a>corpus_neg <span class="op">=</span> [id2word_neg.doc2bow(text) <span class="cf">for</span> text <span class="kw">in</span> texts_neg]</span></code></pre></div>
<div class="sourceCode" id="cb44"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb44-1"><a href="travel-and-accomodation.html#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pprint <span class="im">import</span> pprint</span>
<span id="cb44-2"><a href="travel-and-accomodation.html#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="co"># number of topics</span></span>
<span id="cb44-3"><a href="travel-and-accomodation.html#cb44-3" aria-hidden="true" tabindex="-1"></a>num_topics <span class="op">=</span> <span class="dv">10</span></span>
<span id="cb44-4"><a href="travel-and-accomodation.html#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Build LDA model</span></span>
<span id="cb44-5"><a href="travel-and-accomodation.html#cb44-5" aria-hidden="true" tabindex="-1"></a>lda_model_pos <span class="op">=</span> gensim.models.LdaMulticore(corpus<span class="op">=</span>corpus_pos,</span>
<span id="cb44-6"><a href="travel-and-accomodation.html#cb44-6" aria-hidden="true" tabindex="-1"></a>                                       id2word<span class="op">=</span>id2word_pos,</span>
<span id="cb44-7"><a href="travel-and-accomodation.html#cb44-7" aria-hidden="true" tabindex="-1"></a>                                       num_topics<span class="op">=</span>num_topics)</span>
<span id="cb44-8"><a href="travel-and-accomodation.html#cb44-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-9"><a href="travel-and-accomodation.html#cb44-9" aria-hidden="true" tabindex="-1"></a>lda_model_neg <span class="op">=</span> gensim.models.LdaMulticore(corpus<span class="op">=</span>corpus_neg,</span>
<span id="cb44-10"><a href="travel-and-accomodation.html#cb44-10" aria-hidden="true" tabindex="-1"></a>                                       id2word<span class="op">=</span>id2word_neg,</span>
<span id="cb44-11"><a href="travel-and-accomodation.html#cb44-11" aria-hidden="true" tabindex="-1"></a>                                       num_topics<span class="op">=</span>num_topics)</span></code></pre></div>
<p>Berikut adalah hasil pemilihan 10 kumpulan topik untuk ulasan positif</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb45-1"><a href="travel-and-accomodation.html#cb45-1" aria-hidden="true" tabindex="-1"></a>pprint(lda_model_pos.print_topics())</span></code></pre></div>
<pre><code>#&gt; [(0,
#&gt;   &#39;0.067*&quot;hotel&quot; + 0.035*&quot;staff&quot; + 0.025*&quot;excellent&quot; + 0.023*&quot;room&quot; + &#39;
#&gt;   &#39;0.022*&quot;location&quot; + 0.018*&quot;comfortable&quot; + 0.015*&quot;best&quot; + 0.013*&quot;helpful&quot; + &#39;
#&gt;   &#39;0.012*&quot;recommend&quot; + 0.012*&quot;barcelona&quot;&#39;),
#&gt;  (1,
#&gt;   &#39;0.057*&quot;room&quot; + 0.032*&quot;view&quot; + 0.029*&quot;staff&quot; + 0.025*&quot;hotel&quot; + &#39;
#&gt;   &#39;0.023*&quot;amazing&quot; + 0.019*&quot;great&quot; + 0.019*&quot;lovely&quot; + 0.011*&quot;beautiful&quot; + &#39;
#&gt;   &#39;0.010*&quot;birthday&quot; + 0.010*&quot;friendly&quot;&#39;),
#&gt;  (2,
#&gt;   &#39;0.057*&quot;room&quot; + 0.023*&quot;nice&quot; + 0.021*&quot;hotel&quot; + 0.015*&quot;staff&quot; + 0.014*&quot;check&quot; &#39;
#&gt;   &#39;+ 0.012*&quot;coffee&quot; + 0.012*&quot;free&quot; + 0.009*&quot;good&quot; + 0.008*&quot;small&quot; + &#39;
#&gt;   &#39;0.008*&quot;night&quot;&#39;),
#&gt;  (3,
#&gt;   &#39;0.043*&quot;hotel&quot; + 0.033*&quot;staff&quot; + 0.028*&quot;stay&quot; + 0.028*&quot;service&quot; + &#39;
#&gt;   &#39;0.016*&quot;everything&quot; + 0.016*&quot;time&quot; + 0.012*&quot;every&quot; + 0.012*&quot;excellent&quot; + &#39;
#&gt;   &#39;0.010*&quot;best&quot; + 0.009*&quot;thing&quot;&#39;),
#&gt;  (4,
#&gt;   &#39;0.172*&quot;staff&quot; + 0.106*&quot;friendly&quot; + 0.094*&quot;helpful&quot; + 0.069*&quot;location&quot; + &#39;
#&gt;   &#39;0.038*&quot;great&quot; + 0.030*&quot;room&quot; + 0.025*&quot;hotel&quot; + 0.016*&quot;clean&quot; + 0.014*&quot;nice&quot; &#39;
#&gt;   &#39;+ 0.014*&quot;excellent&quot;&#39;),
#&gt;  (5,
#&gt;   &#39;0.041*&quot;well&quot; + 0.034*&quot;staff&quot; + 0.031*&quot;hotel&quot; + 0.028*&quot;comfy&quot; + 0.025*&quot;room&quot; &#39;
#&gt;   &#39;+ 0.023*&quot;really&quot; + 0.020*&quot;helpful&quot; + 0.016*&quot;great&quot; + 0.013*&quot;like&quot; + &#39;
#&gt;   &#39;0.013*&quot;bed&quot;&#39;),
#&gt;  (6,
#&gt;   &#39;0.107*&quot;breakfast&quot; + 0.087*&quot;good&quot; + 0.052*&quot;location&quot; + 0.052*&quot;staff&quot; + &#39;
#&gt;   &#39;0.042*&quot;excellent&quot; + 0.027*&quot;great&quot; + 0.026*&quot;room&quot; + 0.025*&quot;hotel&quot; + &#39;
#&gt;   &#39;0.021*&quot;friendly&quot; + 0.020*&quot;value&quot;&#39;),
#&gt;  (7,
#&gt;   &#39;0.116*&quot;room&quot; + 0.061*&quot;clean&quot; + 0.060*&quot;location&quot; + 0.056*&quot;comfortable&quot; + &#39;
#&gt;   &#39;0.054*&quot;great&quot; + 0.042*&quot;nice&quot; + 0.041*&quot;good&quot; + 0.035*&quot;staff&quot; + &#39;
#&gt;   &#39;0.023*&quot;excellent&quot; + 0.022*&quot;everything&quot;&#39;),
#&gt;  (8,
#&gt;   &#39;0.078*&quot;hotel&quot; + 0.029*&quot;room&quot; + 0.029*&quot;nice&quot; + 0.022*&quot;design&quot; + &#39;
#&gt;   &#39;0.016*&quot;clean&quot; + 0.014*&quot;staff&quot; + 0.013*&quot;street&quot; + 0.013*&quot;modern&quot; + &#39;
#&gt;   &#39;0.012*&quot;nothing&quot; + 0.011*&quot;liked&quot;&#39;),
#&gt;  (9,
#&gt;   &#39;0.092*&quot;location&quot; + 0.040*&quot;station&quot; + 0.037*&quot;good&quot; + 0.034*&quot;close&quot; + &#39;
#&gt;   &#39;0.026*&quot;great&quot; + 0.026*&quot;metro&quot; + 0.022*&quot;hotel&quot; + 0.019*&quot;walk&quot; + 0.016*&quot;city&quot; &#39;
#&gt;   &#39;+ 0.016*&quot;near&quot;&#39;)]</code></pre>
<p>Berikut adalah hasil pemilihan 10 kumpulan topik untuk ulasan negatif</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb47-1"><a href="travel-and-accomodation.html#cb47-1" aria-hidden="true" tabindex="-1"></a>pprint(lda_model_neg.print_topics())</span></code></pre></div>
<pre><code>#&gt; [(0,
#&gt;   &#39;0.041*&quot;room&quot; + 0.026*&quot;pool&quot; + 0.025*&quot;parking&quot; + 0.023*&quot;window&quot; + &#39;
#&gt;   &#39;0.023*&quot;hotel&quot; + 0.022*&quot;expensive&quot; + 0.021*&quot;noise&quot; + 0.019*&quot;price&quot; + &#39;
#&gt;   &#39;0.019*&quot;night&quot; + 0.014*&quot;open&quot;&#39;),
#&gt;  (1,
#&gt;   &#39;0.036*&quot;room&quot; + 0.030*&quot;bathroom&quot; + 0.030*&quot;coffee&quot; + 0.020*&quot;breakfast&quot; + &#39;
#&gt;   &#39;0.017*&quot;could&quot; + 0.017*&quot;door&quot; + 0.014*&quot;would&quot; + 0.014*&quot;shower&quot; + &#39;
#&gt;   &#39;0.014*&quot;food&quot; + 0.013*&quot;facility&quot;&#39;),
#&gt;  (2,
#&gt;   &#39;0.075*&quot;room&quot; + 0.035*&quot;hotel&quot; + 0.011*&quot;night&quot; + 0.010*&quot;could&quot; + &#39;
#&gt;   &#39;0.009*&quot;booked&quot; + 0.008*&quot;double&quot; + 0.007*&quot;would&quot; + 0.007*&quot;star&quot; + &#39;
#&gt;   &#39;0.007*&quot;staff&quot; + 0.007*&quot;time&quot;&#39;),
#&gt;  (3,
#&gt;   &#39;0.053*&quot;room&quot; + 0.038*&quot;shower&quot; + 0.026*&quot;need&quot; + 0.021*&quot;floor&quot; + &#39;
#&gt;   &#39;0.020*&quot;water&quot; + 0.019*&quot;hotel&quot; + 0.018*&quot;bathroom&quot; + 0.017*&quot;lift&quot; + &#39;
#&gt;   &#39;0.015*&quot;good&quot; + 0.012*&quot;clean&quot;&#39;),
#&gt;  (4,
#&gt;   &#39;0.144*&quot;room&quot; + 0.096*&quot;small&quot; + 0.083*&quot;breakfast&quot; + 0.018*&quot;expensive&quot; + &#39;
#&gt;   &#39;0.015*&quot;little&quot; + 0.014*&quot;view&quot; + 0.014*&quot;size&quot; + 0.011*&quot;price&quot; + &#39;
#&gt;   &#39;0.011*&quot;bathroom&quot; + 0.010*&quot;included&quot;&#39;),
#&gt;  (5,
#&gt;   &#39;0.032*&quot;room&quot; + 0.028*&quot;hotel&quot; + 0.021*&quot;little&quot; + 0.020*&quot;location&quot; + &#39;
#&gt;   &#39;0.018*&quot;could&quot; + 0.016*&quot;area&quot; + 0.013*&quot;pillow&quot; + 0.011*&quot;breakfast&quot; + &#39;
#&gt;   &#39;0.011*&quot;city&quot; + 0.011*&quot;small&quot;&#39;),
#&gt;  (6,
#&gt;   &#39;0.034*&quot;staff&quot; + 0.032*&quot;hotel&quot; + 0.014*&quot;breakfast&quot; + 0.012*&quot;reception&quot; + &#39;
#&gt;   &#39;0.011*&quot;room&quot; + 0.011*&quot;would&quot; + 0.011*&quot;service&quot; + 0.010*&quot;check&quot; + &#39;
#&gt;   &#39;0.009*&quot;time&quot; + 0.008*&quot;booking&quot;&#39;),
#&gt;  (7,
#&gt;   &#39;0.079*&quot;room&quot; + 0.034*&quot;wifi&quot; + 0.016*&quot;time&quot; + 0.012*&quot;free&quot; + 0.012*&quot;check&quot; + &#39;
#&gt;   &#39;0.011*&quot;water&quot; + 0.010*&quot;work&quot; + 0.010*&quot;even&quot; + 0.008*&quot;slow&quot; + 0.008*&quot;cold&quot;&#39;),
#&gt;  (8,
#&gt;   &#39;0.274*&quot;nothing&quot; + 0.058*&quot;everything&quot; + 0.034*&quot;like&quot; + 0.027*&quot;really&quot; + &#39;
#&gt;   &#39;0.021*&quot;perfect&quot; + 0.020*&quot;great&quot; + 0.019*&quot;thing&quot; + 0.016*&quot;hotel&quot; + &#39;
#&gt;   &#39;0.016*&quot;anything&quot; + 0.014*&quot;good&quot;&#39;),
#&gt;  (9,
#&gt;   &#39;0.074*&quot;room&quot; + 0.027*&quot;night&quot; + 0.025*&quot;noisy&quot; + 0.017*&quot;service&quot; + &#39;
#&gt;   &#39;0.015*&quot;floor&quot; + 0.014*&quot;hotel&quot; + 0.012*&quot;morning&quot; + 0.012*&quot;door&quot; + &#39;
#&gt;   &#39;0.010*&quot;work&quot; + 0.009*&quot;noise&quot;&#39;)]</code></pre>
<p>Berikut adalah potongan kode untuk melakukan visualisasi pemilihan topik dengan model LDA.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb49-1"><a href="travel-and-accomodation.html#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize the topics</span></span>
<span id="cb49-2"><a href="travel-and-accomodation.html#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="travel-and-accomodation.html#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> ldaviz(lda_model, corpus, id2word, num_topics, filename):</span>
<span id="cb49-4"><a href="travel-and-accomodation.html#cb49-4" aria-hidden="true" tabindex="-1"></a>    pyLDAvis.enable_notebook()</span>
<span id="cb49-5"><a href="travel-and-accomodation.html#cb49-5" aria-hidden="true" tabindex="-1"></a>    LDAvis_data_filepath <span class="op">=</span> os.path.join(os.getcwd()<span class="op">+</span><span class="bu">str</span>(num_topics))</span>
<span id="cb49-6"><a href="travel-and-accomodation.html#cb49-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># # this is a bit time consuming - make the if statement True</span></span>
<span id="cb49-7"><a href="travel-and-accomodation.html#cb49-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># # if you want to execute visualization prep yourself</span></span>
<span id="cb49-8"><a href="travel-and-accomodation.html#cb49-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="va">True</span>:</span>
<span id="cb49-9"><a href="travel-and-accomodation.html#cb49-9" aria-hidden="true" tabindex="-1"></a>        LDAvis_prepared <span class="op">=</span> pyLDAvis.gensim.prepare(lda_model, corpus, id2word)</span>
<span id="cb49-10"><a href="travel-and-accomodation.html#cb49-10" aria-hidden="true" tabindex="-1"></a>        <span class="cf">with</span> <span class="bu">open</span>(LDAvis_data_filepath, <span class="st">&#39;wb&#39;</span>) <span class="im">as</span> f:</span>
<span id="cb49-11"><a href="travel-and-accomodation.html#cb49-11" aria-hidden="true" tabindex="-1"></a>            pickle.dump(LDAvis_prepared, f)</span>
<span id="cb49-12"><a href="travel-and-accomodation.html#cb49-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># load the pre-prepared pyLDAvis data from disk</span></span>
<span id="cb49-13"><a href="travel-and-accomodation.html#cb49-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> <span class="bu">open</span>(LDAvis_data_filepath, <span class="st">&#39;rb&#39;</span>) <span class="im">as</span> f:</span>
<span id="cb49-14"><a href="travel-and-accomodation.html#cb49-14" aria-hidden="true" tabindex="-1"></a>        LDAvis_prepared <span class="op">=</span> pickle.load(f)</span>
<span id="cb49-15"><a href="travel-and-accomodation.html#cb49-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> pyLDAvis.save_html(LDAvis_prepared, os.getcwd()<span class="op">+</span> <span class="st">&#39;/&#39;</span> <span class="op">+</span> filename <span class="op">+</span><span class="st">&#39;.html&#39;</span>)</span>
<span id="cb49-16"><a href="travel-and-accomodation.html#cb49-16" aria-hidden="true" tabindex="-1"></a>    <span class="co">#return LDAvis_prepared</span></span></code></pre></div>
<div class="sourceCode" id="cb50"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb50-1"><a href="travel-and-accomodation.html#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualization for Positive Reviews</span></span>
<span id="cb50-2"><a href="travel-and-accomodation.html#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ldaviz(lda_model_pos, corpus_pos, id2word_pos, num_topics, &#39;ldavizpos&#39;)</span></span></code></pre></div>
<div class="sourceCode" id="cb51"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb51-1"><a href="travel-and-accomodation.html#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualization for Negative Reviews</span></span>
<span id="cb51-2"><a href="travel-and-accomodation.html#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="co"># daviz(lda_model_neg, corpus_neg, id2word_neg, num_topics, &#39;ldavizneg&#39;)</span></span></code></pre></div>
<p>Topik-topik tersebut di <em>extract</em> dan dihitung skor kumulatif untuk masing-masing topik.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb52-1"><a href="travel-and-accomodation.html#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract all topics from negative and positive</span></span>
<span id="cb52-2"><a href="travel-and-accomodation.html#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="travel-and-accomodation.html#cb52-3" aria-hidden="true" tabindex="-1"></a>topics_pos <span class="op">=</span> []</span>
<span id="cb52-4"><a href="travel-and-accomodation.html#cb52-4" aria-hidden="true" tabindex="-1"></a>topics_neg <span class="op">=</span> []</span>
<span id="cb52-5"><a href="travel-and-accomodation.html#cb52-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-6"><a href="travel-and-accomodation.html#cb52-6" aria-hidden="true" tabindex="-1"></a>scores_pos <span class="op">=</span> []</span>
<span id="cb52-7"><a href="travel-and-accomodation.html#cb52-7" aria-hidden="true" tabindex="-1"></a>scores_neg <span class="op">=</span> []</span>
<span id="cb52-8"><a href="travel-and-accomodation.html#cb52-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-9"><a href="travel-and-accomodation.html#cb52-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> pos, neg <span class="kw">in</span> <span class="bu">zip</span>(lda_model_pos.print_topics(), lda_model_neg.print_topics()):</span>
<span id="cb52-10"><a href="travel-and-accomodation.html#cb52-10" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb52-11"><a href="travel-and-accomodation.html#cb52-11" aria-hidden="true" tabindex="-1"></a>    topic_pos <span class="op">=</span> re.findall(<span class="st">&quot;(?&lt;=</span><span class="ch">\&quot;</span><span class="st">)[a-z]+(?=</span><span class="ch">\&quot;</span><span class="st">)&quot;</span>,pos[<span class="dv">1</span>])</span>
<span id="cb52-12"><a href="travel-and-accomodation.html#cb52-12" aria-hidden="true" tabindex="-1"></a>    topics_pos <span class="op">=</span> topics_pos <span class="op">+</span> topic_pos</span>
<span id="cb52-13"><a href="travel-and-accomodation.html#cb52-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb52-14"><a href="travel-and-accomodation.html#cb52-14" aria-hidden="true" tabindex="-1"></a>    score_pos <span class="op">=</span> re.findall(<span class="st">&quot;\d\.\d+&quot;</span>,pos[<span class="dv">1</span>])</span>
<span id="cb52-15"><a href="travel-and-accomodation.html#cb52-15" aria-hidden="true" tabindex="-1"></a>    scores_pos <span class="op">=</span> scores_pos <span class="op">+</span> score_pos</span>
<span id="cb52-16"><a href="travel-and-accomodation.html#cb52-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-17"><a href="travel-and-accomodation.html#cb52-17" aria-hidden="true" tabindex="-1"></a>    topic_neg <span class="op">=</span> re.findall(<span class="st">&quot;(?&lt;=</span><span class="ch">\&quot;</span><span class="st">)[a-z]+(?=</span><span class="ch">\&quot;</span><span class="st">)&quot;</span>,neg[<span class="dv">1</span>])</span>
<span id="cb52-18"><a href="travel-and-accomodation.html#cb52-18" aria-hidden="true" tabindex="-1"></a>    topics_neg <span class="op">=</span> topics_neg <span class="op">+</span> topic_neg</span>
<span id="cb52-19"><a href="travel-and-accomodation.html#cb52-19" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb52-20"><a href="travel-and-accomodation.html#cb52-20" aria-hidden="true" tabindex="-1"></a>    score_neg <span class="op">=</span> re.findall(<span class="st">&quot;\d\.\d+&quot;</span>,pos[<span class="dv">1</span>])</span>
<span id="cb52-21"><a href="travel-and-accomodation.html#cb52-21" aria-hidden="true" tabindex="-1"></a>    scores_neg <span class="op">=</span> scores_neg <span class="op">+</span> score_neg</span>
<span id="cb52-22"><a href="travel-and-accomodation.html#cb52-22" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb52-23"><a href="travel-and-accomodation.html#cb52-23" aria-hidden="true" tabindex="-1"></a>positive_topics <span class="op">=</span> pd.DataFrame({<span class="st">&#39;Topics&#39;</span>:topics_pos, <span class="st">&#39;Score&#39;</span>:scores_pos})</span>
<span id="cb52-24"><a href="travel-and-accomodation.html#cb52-24" aria-hidden="true" tabindex="-1"></a>positive_topics[<span class="st">&#39;Score&#39;</span>] <span class="op">=</span> positive_topics[<span class="st">&#39;Score&#39;</span>].astype(<span class="bu">float</span>)</span>
<span id="cb52-25"><a href="travel-and-accomodation.html#cb52-25" aria-hidden="true" tabindex="-1"></a>positive_topics <span class="op">=</span> positive_topics.groupby(<span class="st">&#39;Topics&#39;</span>).<span class="bu">sum</span>().reset_index()<span class="op">\</span></span>
<span id="cb52-26"><a href="travel-and-accomodation.html#cb52-26" aria-hidden="true" tabindex="-1"></a>.sort_values(<span class="st">&#39;Score&#39;</span>,ascending <span class="op">=</span> <span class="va">False</span>)</span>
<span id="cb52-27"><a href="travel-and-accomodation.html#cb52-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-28"><a href="travel-and-accomodation.html#cb52-28" aria-hidden="true" tabindex="-1"></a>negative_topics <span class="op">=</span> pd.DataFrame({<span class="st">&#39;Topics&#39;</span>:topics_neg, <span class="st">&#39;Score&#39;</span>:scores_neg})</span>
<span id="cb52-29"><a href="travel-and-accomodation.html#cb52-29" aria-hidden="true" tabindex="-1"></a>negative_topics[<span class="st">&#39;Score&#39;</span>] <span class="op">=</span> negative_topics[<span class="st">&#39;Score&#39;</span>].astype(<span class="bu">float</span>)</span>
<span id="cb52-30"><a href="travel-and-accomodation.html#cb52-30" aria-hidden="true" tabindex="-1"></a>negative_topics <span class="op">=</span> negative_topics.groupby(<span class="st">&#39;Topics&#39;</span>).<span class="bu">sum</span>().reset_index()<span class="op">\</span></span>
<span id="cb52-31"><a href="travel-and-accomodation.html#cb52-31" aria-hidden="true" tabindex="-1"></a>.sort_values(<span class="st">&#39;Score&#39;</span>,ascending <span class="op">=</span> <span class="va">False</span>)</span></code></pre></div>
<p>Maka diperoleh kumpulan topik beserta <em>score</em> seberapa relevan suatu topik terhadap ulasan yang diberikan yang ditabulasikan sebagai berikut.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb53-1"><a href="travel-and-accomodation.html#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#inner join to see topics that belongs to each other</span></span>
<span id="cb53-2"><a href="travel-and-accomodation.html#cb53-2" aria-hidden="true" tabindex="-1"></a>pd.merge(positive_topics, negative_topics, <span class="st">&#39;inner&#39;</span>, <span class="st">&#39;Topics&#39;</span>)</span></code></pre></div>
<pre><code>#&gt;         Topics  Score_x  Score_y
#&gt; 0        staff    0.419    0.115
#&gt; 1         room    0.363    0.687
#&gt; 2        hotel    0.337    0.221
#&gt; 3     location    0.295    0.028
#&gt; 4        great    0.180    0.014
#&gt; 5         good    0.174    0.021
#&gt; 6    breakfast    0.107    0.187
#&gt; 7        clean    0.093    0.009
#&gt; 8   everything    0.038    0.029
#&gt; 9         view    0.032    0.030
#&gt; 10     service    0.028    0.060
#&gt; 11      really    0.023    0.022
#&gt; 12        city    0.016    0.013
#&gt; 13        time    0.016    0.089
#&gt; 14       check    0.014    0.079
#&gt; 15        like    0.013    0.029
#&gt; 16      coffee    0.012    0.029
#&gt; 17     nothing    0.012    0.078
#&gt; 18        free    0.012    0.056
#&gt; 19       thing    0.009    0.013
#&gt; 20       small    0.008    0.119
#&gt; 21       night    0.008    0.073</code></pre>
<p>Dalam hal ini, kita dapat memilih secara manual atau memilih dengan mengambil topik dengan skor yang paling besar. Tahap ini disebut <em>Topic Labelling</em>. Namun dalam hal ini kita cukup memilih topik secara manual dengan mengandalkan pengetahuan kita mengenai fasilitas apa yang sering atau selalu disediakan oleh pihak hotel.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb55-1"><a href="travel-and-accomodation.html#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Topic labelling</span></span>
<span id="cb55-2"><a href="travel-and-accomodation.html#cb55-2" aria-hidden="true" tabindex="-1"></a>aspects <span class="op">=</span> [<span class="st">&#39;staff&#39;</span>, <span class="st">&#39;room&#39;</span>, <span class="st">&#39;breakfast&#39;</span>, <span class="st">&#39;service&#39;</span>, <span class="st">&#39;view&#39;</span>, <span class="st">&#39;restaurant&#39;</span>, <span class="st">&#39;bathroom&#39;</span>, <span class="st">&#39;pool&#39;</span>]</span></code></pre></div>
<p>Untuk memperoleh hasil yang merepresentasikan tiap hotel, alangkah lebih semua review dijadikan menjadi satu dokumen untuk tiap hotel. Sehingga kita dapat memperoleh satu buah dokumen penuh berisi review untuk tiap-tiap hotel.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb56-1"><a href="travel-and-accomodation.html#cb56-1" aria-hidden="true" tabindex="-1"></a>df_reviews <span class="op">=</span> df_reviews.groupby(<span class="st">&#39;Hotel_Name&#39;</span>)[<span class="st">&#39;Negative_Review&#39;</span>,<span class="st">&#39;Positive_Review&#39;</span>].<span class="bu">sum</span>()</span></code></pre></div>
<p>Dari aspek-aspek ini, kita akan menentukan <em>word correlation</em> dari aspek yang kita inginkan, yaitu mencari kata sebelum dan sesudah dari topik yang diinginkan. Hal ini bertujuan untuk melihat hubungan dari aspek (fasilitas) yang diberikan hotel terhadap kata yang diberikan oleh wisatawan melalui ulasannnya. Sebagai contoh, kita ingin melihat ruangan, namun kita perlu tahu ruangan itu seperti apa menurut para wisatawan. Bisa jadi ruangan itu baik, buruk, sempit, luas, mengecewakan, dan lain-lain. Metode ini bernama <em>ngram</em> yaitu <strong>memasangkan kata dengan kata disebelahnya (baik sebelum atau sesudahnya)</strong>.</p>
<p>Kita ambil contoh untuk satu dokumen (satu buah hotel). Misalkan aspek yang ingin dilihat adalah <strong>room</strong> dengan jumlah kata dalam satu pasangan <strong>n</strong> adalah 2.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb57-1"><a href="travel-and-accomodation.html#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># let&#39;s take a look at example</span></span>
<span id="cb57-2"><a href="travel-and-accomodation.html#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="co"># if we want to extract only room</span></span>
<span id="cb57-3"><a href="travel-and-accomodation.html#cb57-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-4"><a href="travel-and-accomodation.html#cb57-4" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">2</span></span>
<span id="cb57-5"><a href="travel-and-accomodation.html#cb57-5" aria-hidden="true" tabindex="-1"></a>example <span class="op">=</span> df_reviews[<span class="st">&#39;Negative_Review&#39;</span>][<span class="dv">2</span>]</span>
<span id="cb57-6"><a href="travel-and-accomodation.html#cb57-6" aria-hidden="true" tabindex="-1"></a>terms_ngram <span class="op">=</span> [<span class="bu">list</span>(ngrams(w,n)) <span class="cf">for</span> w <span class="kw">in</span> [example]]</span>
<span id="cb57-7"><a href="travel-and-accomodation.html#cb57-7" aria-hidden="true" tabindex="-1"></a>room_ngram <span class="op">=</span> [i <span class="cf">for</span> i <span class="kw">in</span> terms_ngram[<span class="dv">0</span>] <span class="cf">if</span> <span class="st">&#39;room&#39;</span> <span class="kw">in</span> i]</span>
<span id="cb57-8"><a href="travel-and-accomodation.html#cb57-8" aria-hidden="true" tabindex="-1"></a>room_ngram[:<span class="dv">5</span>]</span></code></pre></div>
<pre><code>#&gt; [(&#39;disappointing&#39;, &#39;room&#39;), (&#39;room&#39;, &#39;really&#39;), (&#39;time&#39;, &#39;room&#39;), (&#39;room&#39;, &#39;furniture&#39;), (&#39;special&#39;, &#39;room&#39;)]</code></pre>
<p>Untuk mendapatkan sebagian dokumen yang hanya membicarakan <strong>room</strong>, kita perlu menggabungkan semua <strong>ngram</strong> menjadi satu dokumen dengan metode <strong>chain</strong>.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb59-1"><a href="travel-and-accomodation.html#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Flatten list of room ngrams in clean list</span></span>
<span id="cb59-2"><a href="travel-and-accomodation.html#cb59-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-3"><a href="travel-and-accomodation.html#cb59-3" aria-hidden="true" tabindex="-1"></a>room_ngram_flatten <span class="op">=</span> <span class="bu">list</span>(itertools.chain(<span class="op">*</span>room_ngram))</span>
<span id="cb59-4"><a href="travel-and-accomodation.html#cb59-4" aria-hidden="true" tabindex="-1"></a>room_ngram_flatten[:<span class="dv">6</span>]</span></code></pre></div>
<pre><code>#&gt; [&#39;disappointing&#39;, &#39;room&#39;, &#39;room&#39;, &#39;really&#39;, &#39;time&#39;, &#39;room&#39;]</code></pre>
<p>Kita dapat menghitung jumlah pasangan kata yang sama dalam satu dokumen dengan menggunakan <em>method</em> <strong>collections.Counter</strong>.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb61-1"><a href="travel-and-accomodation.html#cb61-1" aria-hidden="true" tabindex="-1"></a>ngram_counts <span class="op">=</span> collections.Counter(room_ngram)</span>
<span id="cb61-2"><a href="travel-and-accomodation.html#cb61-2" aria-hidden="true" tabindex="-1"></a>ngram_df <span class="op">=</span> pd.DataFrame(ngram_counts.most_common(<span class="dv">20</span>),</span>
<span id="cb61-3"><a href="travel-and-accomodation.html#cb61-3" aria-hidden="true" tabindex="-1"></a>                             columns<span class="op">=</span>[<span class="st">&#39;ngram&#39;</span>, <span class="st">&#39;count&#39;</span>])</span>
<span id="cb61-4"><a href="travel-and-accomodation.html#cb61-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-5"><a href="travel-and-accomodation.html#cb61-5" aria-hidden="true" tabindex="-1"></a>ngram_df.head()</span></code></pre></div>
<pre><code>#&gt;              ngram  count
#&gt; 0    (room, small)     27
#&gt; 1    (small, room)     19
#&gt; 2   (room, little)     10
#&gt; 3  (room, service)      7
#&gt; 4   (room, really)      6</code></pre>
<p>Setelah itu, kita akan melakukan visualisasi mengenai <strong>word correlation</strong> dari aspek <strong>room</strong> yang kita pilih sebelumnya dengan bantuan <em>library</em> <strong>networkx</strong>. Sebelum, melakukan visualisasi, tabel frekuensi <strong>ngram_df</strong> alangkah lebih baik diubah ke dalam bentuk <em>dictionary</em>. Hasil dari visualisasi i ni menampilkan korelasi kata-kata terhadap aspek yang kita pilih. Semakin dekat kata-kata tersebut satu sama lain, semakin tinggi frekuensi dari kemunculan pasangan kata tersebut.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb63-1"><a href="travel-and-accomodation.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># we visualize</span></span>
<span id="cb63-2"><a href="travel-and-accomodation.html#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="co"># transform to dict first</span></span>
<span id="cb63-3"><a href="travel-and-accomodation.html#cb63-3" aria-hidden="true" tabindex="-1"></a>d <span class="op">=</span> ngram_df.set_index(<span class="st">&#39;ngram&#39;</span>).T.to_dict(<span class="st">&#39;records&#39;</span>)</span>
<span id="cb63-4"><a href="travel-and-accomodation.html#cb63-4" aria-hidden="true" tabindex="-1"></a>d[<span class="dv">0</span>]</span></code></pre></div>
<pre><code>#&gt; {(&#39;room&#39;, &#39;small&#39;): 27, (&#39;small&#39;, &#39;room&#39;): 19, (&#39;room&#39;, &#39;little&#39;): 10, (&#39;room&#39;, &#39;service&#39;): 7, (&#39;room&#39;, &#39;really&#39;): 6, (&#39;facility&#39;, &#39;room&#39;): 6, (&#39;room&#39;, &#39;room&#39;): 6, (&#39;room&#39;, &#39;could&#39;): 5, (&#39;room&#39;, &#39;quite&#39;): 5, (&#39;room&#39;, &#39;floor&#39;): 5, (&#39;clothes&#39;, &#39;room&#39;): 4, (&#39;kettle&#39;, &#39;room&#39;): 4, (&#39;room&#39;, &#39;night&#39;): 4, (&#39;view&#39;, &#39;room&#39;): 4, (&#39;room&#39;, &#39;breakfast&#39;): 4, (&#39;machine&#39;, &#39;room&#39;): 4, (&#39;great&#39;, &#39;room&#39;): 3, (&#39;room&#39;, &#39;size&#39;): 3, (&#39;chair&#39;, &#39;room&#39;): 3, (&#39;standard&#39;, &#39;room&#39;): 3}</code></pre>
<div class="sourceCode" id="cb65"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb65-1"><a href="travel-and-accomodation.html#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create network plot </span></span>
<span id="cb65-2"><a href="travel-and-accomodation.html#cb65-2" aria-hidden="true" tabindex="-1"></a>G <span class="op">=</span> nx.Graph()</span>
<span id="cb65-3"><a href="travel-and-accomodation.html#cb65-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-4"><a href="travel-and-accomodation.html#cb65-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create connections between nodes</span></span>
<span id="cb65-5"><a href="travel-and-accomodation.html#cb65-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k, v <span class="kw">in</span> d[<span class="dv">0</span>].items():</span>
<span id="cb65-6"><a href="travel-and-accomodation.html#cb65-6" aria-hidden="true" tabindex="-1"></a>    G.add_edge(k[<span class="dv">0</span>], k[<span class="dv">1</span>], weight<span class="op">=</span>(v <span class="op">*</span> <span class="dv">10</span>))</span>
<span id="cb65-7"><a href="travel-and-accomodation.html#cb65-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-8"><a href="travel-and-accomodation.html#cb65-8" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">8</span>))</span>
<span id="cb65-9"><a href="travel-and-accomodation.html#cb65-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-10"><a href="travel-and-accomodation.html#cb65-10" aria-hidden="true" tabindex="-1"></a>pos <span class="op">=</span> nx.spring_layout(G, k<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb65-11"><a href="travel-and-accomodation.html#cb65-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-12"><a href="travel-and-accomodation.html#cb65-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot networks</span></span>
<span id="cb65-13"><a href="travel-and-accomodation.html#cb65-13" aria-hidden="true" tabindex="-1"></a>nx.draw_networkx(G, pos,</span>
<span id="cb65-14"><a href="travel-and-accomodation.html#cb65-14" aria-hidden="true" tabindex="-1"></a>                 font_size<span class="op">=</span><span class="dv">16</span>,</span>
<span id="cb65-15"><a href="travel-and-accomodation.html#cb65-15" aria-hidden="true" tabindex="-1"></a>                 width<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb65-16"><a href="travel-and-accomodation.html#cb65-16" aria-hidden="true" tabindex="-1"></a>                 edge_color<span class="op">=</span><span class="st">&#39;grey&#39;</span>,</span>
<span id="cb65-17"><a href="travel-and-accomodation.html#cb65-17" aria-hidden="true" tabindex="-1"></a>                 node_color<span class="op">=</span><span class="st">&#39;purple&#39;</span>,</span>
<span id="cb65-18"><a href="travel-and-accomodation.html#cb65-18" aria-hidden="true" tabindex="-1"></a>                 with_labels <span class="op">=</span> <span class="va">False</span>,</span>
<span id="cb65-19"><a href="travel-and-accomodation.html#cb65-19" aria-hidden="true" tabindex="-1"></a>                 ax<span class="op">=</span>ax)</span>
<span id="cb65-20"><a href="travel-and-accomodation.html#cb65-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-21"><a href="travel-and-accomodation.html#cb65-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Create offset labels</span></span>
<span id="cb65-22"><a href="travel-and-accomodation.html#cb65-22" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> key, value <span class="kw">in</span> pos.items():</span>
<span id="cb65-23"><a href="travel-and-accomodation.html#cb65-23" aria-hidden="true" tabindex="-1"></a>    x, y <span class="op">=</span> value[<span class="dv">0</span>]<span class="op">+</span><span class="fl">.135</span>, value[<span class="dv">1</span>]<span class="op">+</span><span class="fl">.045</span></span>
<span id="cb65-24"><a href="travel-and-accomodation.html#cb65-24" aria-hidden="true" tabindex="-1"></a>    ax.text(x, y,</span>
<span id="cb65-25"><a href="travel-and-accomodation.html#cb65-25" aria-hidden="true" tabindex="-1"></a>            s<span class="op">=</span>key,</span>
<span id="cb65-26"><a href="travel-and-accomodation.html#cb65-26" aria-hidden="true" tabindex="-1"></a>            bbox<span class="op">=</span><span class="bu">dict</span>(facecolor<span class="op">=</span><span class="st">&#39;red&#39;</span>, alpha<span class="op">=</span><span class="fl">0.25</span>),</span>
<span id="cb65-27"><a href="travel-and-accomodation.html#cb65-27" aria-hidden="true" tabindex="-1"></a>            horizontalalignment<span class="op">=</span><span class="st">&#39;center&#39;</span>, fontsize<span class="op">=</span><span class="dv">13</span>)</span>
<span id="cb65-28"><a href="travel-and-accomodation.html#cb65-28" aria-hidden="true" tabindex="-1"></a>    </span></code></pre></div>
<pre><code>#&gt; Text(0.14436154090192493, 0.06555010897030616, &#39;room&#39;)
#&gt; Text(0.28680637251916874, -0.17276045649959254, &#39;small&#39;)
#&gt; Text(0.47002549236053687, 0.25281448052717426, &#39;little&#39;)
#&gt; Text(-0.01847479663151988, -0.4204990266494702, &#39;service&#39;)
#&gt; Text(-0.3705627484918037, -0.046311204674404194, &#39;really&#39;)
#&gt; Text(0.3338863524039992, 0.6175683243713621, &#39;facility&#39;)
#&gt; Text(0.8250464326914789, -0.03044772100437307, &#39;could&#39;)
#&gt; Text(-0.10193372231177167, 0.6471794795180892, &#39;quite&#39;)
#&gt; Text(-0.47186554967651484, 0.3415539660921315, &#39;floor&#39;)
#&gt; Text(-0.44472746553720455, 0.7377357891708914, &#39;clothes&#39;)
#&gt; Text(0.863841141665385, -0.37479852558852506, &#39;kettle&#39;)
#&gt; Text(-0.5643140145322153, -0.3907875873310931, &#39;night&#39;)
#&gt; Text(0.1692306925681048, 0.9618663785160028, &#39;view&#39;)
#&gt; Text(0.9868681356503629, 0.3148908193849318, &#39;breakfast&#39;)
#&gt; Text(0.7444601619841278, 0.7061054057529598, &#39;machine&#39;)
#&gt; Text(0.21873476803355257, -0.8945533008493735, &#39;great&#39;)
#&gt; Text(0.672590186510921, -0.7501811063538283, &#39;size&#39;)
#&gt; Text(-0.8649999999999999, 0.10037108836747693, &#39;chair&#39;)
#&gt; Text(-0.31397298010853186, -0.8102969117206656, &#39;standard&#39;)</code></pre>
<div class="sourceCode" id="cb67"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb67-1"><a href="travel-and-accomodation.html#cb67-1" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div>
<p><img src="bookmlindustry_files/figure-html/unnamed-chunk-3-13.png" width="960" style="display: block; margin: auto;" /></p>
<p>Agar <em>script</em> dapat digunakan berulang-ulang, alangkah lebih baik jika dimuat dalam bentuk <em>function</em>. Dengan <em>function</em>, kita juga dapat mengganti nilai <strong>n</strong> dalam <strong>ngrams</strong> sesuai kebutuhan.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb68-1"><a href="travel-and-accomodation.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co">## create functions to be utilized for further observation</span></span>
<span id="cb68-2"><a href="travel-and-accomodation.html#cb68-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-3"><a href="travel-and-accomodation.html#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to create ngrams (for only 1 topics)</span></span>
<span id="cb68-4"><a href="travel-and-accomodation.html#cb68-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> create_ngrams(text_array, n, aspect):</span>
<span id="cb68-5"><a href="travel-and-accomodation.html#cb68-5" aria-hidden="true" tabindex="-1"></a>    terms_ngram <span class="op">=</span> [<span class="bu">list</span>(ngrams(w,n)) <span class="cf">for</span> w <span class="kw">in</span> [text_array]]</span>
<span id="cb68-6"><a href="travel-and-accomodation.html#cb68-6" aria-hidden="true" tabindex="-1"></a>    ngram <span class="op">=</span> [i <span class="cf">for</span> i <span class="kw">in</span> terms_ngram[<span class="dv">0</span>] <span class="cf">if</span> aspect <span class="kw">in</span> i]</span>
<span id="cb68-7"><a href="travel-and-accomodation.html#cb68-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> ngram</span>
<span id="cb68-8"><a href="travel-and-accomodation.html#cb68-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-9"><a href="travel-and-accomodation.html#cb68-9" aria-hidden="true" tabindex="-1"></a><span class="co">#create_ngrams(example, 2, aspect = &#39;room&#39;)</span></span>
<span id="cb68-10"><a href="travel-and-accomodation.html#cb68-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-11"><a href="travel-and-accomodation.html#cb68-11" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> ngrams_flatten(ngram):</span>
<span id="cb68-12"><a href="travel-and-accomodation.html#cb68-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Flatten list of bigrams in clean tweets</span></span>
<span id="cb68-13"><a href="travel-and-accomodation.html#cb68-13" aria-hidden="true" tabindex="-1"></a>    ngram <span class="op">=</span> <span class="bu">list</span>(itertools.chain(<span class="op">*</span>ngram))</span>
<span id="cb68-14"><a href="travel-and-accomodation.html#cb68-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> ngram</span>
<span id="cb68-15"><a href="travel-and-accomodation.html#cb68-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-16"><a href="travel-and-accomodation.html#cb68-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to count the frequency</span></span>
<span id="cb68-17"><a href="travel-and-accomodation.html#cb68-17" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> ngrams_frequency(ngram,  num_most_common):</span>
<span id="cb68-18"><a href="travel-and-accomodation.html#cb68-18" aria-hidden="true" tabindex="-1"></a>    ngram_counts <span class="op">=</span> collections.Counter(ngram)</span>
<span id="cb68-19"><a href="travel-and-accomodation.html#cb68-19" aria-hidden="true" tabindex="-1"></a>    ngram_df <span class="op">=</span> pd.DataFrame(ngram_counts.most_common(num_most_common),</span>
<span id="cb68-20"><a href="travel-and-accomodation.html#cb68-20" aria-hidden="true" tabindex="-1"></a>                             columns<span class="op">=</span>[<span class="st">&#39;ngram&#39;</span>, <span class="st">&#39;count&#39;</span>])</span>
<span id="cb68-21"><a href="travel-and-accomodation.html#cb68-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> ngram_df</span>
<span id="cb68-22"><a href="travel-and-accomodation.html#cb68-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-23"><a href="travel-and-accomodation.html#cb68-23" aria-hidden="true" tabindex="-1"></a><span class="co">#ngrams_frequency(create_ngrams(example, 2, aspect = &#39;room&#39;), 10)</span></span>
<span id="cb68-24"><a href="travel-and-accomodation.html#cb68-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-25"><a href="travel-and-accomodation.html#cb68-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Create network plot </span></span>
<span id="cb68-26"><a href="travel-and-accomodation.html#cb68-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-27"><a href="travel-and-accomodation.html#cb68-27" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_network(dataframe):</span>
<span id="cb68-28"><a href="travel-and-accomodation.html#cb68-28" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb68-29"><a href="travel-and-accomodation.html#cb68-29" aria-hidden="true" tabindex="-1"></a>    <span class="cf">try</span>:</span>
<span id="cb68-30"><a href="travel-and-accomodation.html#cb68-30" aria-hidden="true" tabindex="-1"></a>        <span class="co"># transform to dict first</span></span>
<span id="cb68-31"><a href="travel-and-accomodation.html#cb68-31" aria-hidden="true" tabindex="-1"></a>        d <span class="op">=</span> dataframe.set_index(<span class="st">&#39;ngram&#39;</span>).T.to_dict(<span class="st">&#39;records&#39;</span>)</span>
<span id="cb68-32"><a href="travel-and-accomodation.html#cb68-32" aria-hidden="true" tabindex="-1"></a>        d[<span class="dv">0</span>]</span>
<span id="cb68-33"><a href="travel-and-accomodation.html#cb68-33" aria-hidden="true" tabindex="-1"></a>        G <span class="op">=</span> nx.Graph()</span>
<span id="cb68-34"><a href="travel-and-accomodation.html#cb68-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-35"><a href="travel-and-accomodation.html#cb68-35" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Create connections between nodes</span></span>
<span id="cb68-36"><a href="travel-and-accomodation.html#cb68-36" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> k, v <span class="kw">in</span> d[<span class="dv">0</span>].items():</span>
<span id="cb68-37"><a href="travel-and-accomodation.html#cb68-37" aria-hidden="true" tabindex="-1"></a>            G.add_edge(k[<span class="dv">0</span>], k[<span class="dv">1</span>], weight<span class="op">=</span>(v <span class="op">*</span> <span class="dv">10</span>))</span>
<span id="cb68-38"><a href="travel-and-accomodation.html#cb68-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-39"><a href="travel-and-accomodation.html#cb68-39" aria-hidden="true" tabindex="-1"></a>        fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">8</span>))</span>
<span id="cb68-40"><a href="travel-and-accomodation.html#cb68-40" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb68-41"><a href="travel-and-accomodation.html#cb68-41" aria-hidden="true" tabindex="-1"></a>        pos <span class="op">=</span> nx.spring_layout(G, k<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb68-42"><a href="travel-and-accomodation.html#cb68-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-43"><a href="travel-and-accomodation.html#cb68-43" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Plot networks</span></span>
<span id="cb68-44"><a href="travel-and-accomodation.html#cb68-44" aria-hidden="true" tabindex="-1"></a>        nx.draw_networkx(G, pos,</span>
<span id="cb68-45"><a href="travel-and-accomodation.html#cb68-45" aria-hidden="true" tabindex="-1"></a>                         font_size<span class="op">=</span><span class="dv">16</span>,</span>
<span id="cb68-46"><a href="travel-and-accomodation.html#cb68-46" aria-hidden="true" tabindex="-1"></a>                         width<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb68-47"><a href="travel-and-accomodation.html#cb68-47" aria-hidden="true" tabindex="-1"></a>                         edge_color<span class="op">=</span><span class="st">&#39;grey&#39;</span>,</span>
<span id="cb68-48"><a href="travel-and-accomodation.html#cb68-48" aria-hidden="true" tabindex="-1"></a>                         node_color<span class="op">=</span><span class="st">&#39;purple&#39;</span>,</span>
<span id="cb68-49"><a href="travel-and-accomodation.html#cb68-49" aria-hidden="true" tabindex="-1"></a>                         with_labels <span class="op">=</span> <span class="va">False</span>,</span>
<span id="cb68-50"><a href="travel-and-accomodation.html#cb68-50" aria-hidden="true" tabindex="-1"></a>                         ax<span class="op">=</span>ax)</span>
<span id="cb68-51"><a href="travel-and-accomodation.html#cb68-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-52"><a href="travel-and-accomodation.html#cb68-52" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Create offset labels</span></span>
<span id="cb68-53"><a href="travel-and-accomodation.html#cb68-53" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> key, value <span class="kw">in</span> pos.items():</span>
<span id="cb68-54"><a href="travel-and-accomodation.html#cb68-54" aria-hidden="true" tabindex="-1"></a>            x, y <span class="op">=</span> value[<span class="dv">0</span>]<span class="op">+</span><span class="fl">.135</span>, value[<span class="dv">1</span>]<span class="op">+</span><span class="fl">.045</span></span>
<span id="cb68-55"><a href="travel-and-accomodation.html#cb68-55" aria-hidden="true" tabindex="-1"></a>            ax.text(x, y,</span>
<span id="cb68-56"><a href="travel-and-accomodation.html#cb68-56" aria-hidden="true" tabindex="-1"></a>                    s<span class="op">=</span>key,</span>
<span id="cb68-57"><a href="travel-and-accomodation.html#cb68-57" aria-hidden="true" tabindex="-1"></a>                    bbox<span class="op">=</span><span class="bu">dict</span>(facecolor<span class="op">=</span><span class="st">&#39;red&#39;</span>, alpha<span class="op">=</span><span class="fl">0.25</span>),</span>
<span id="cb68-58"><a href="travel-and-accomodation.html#cb68-58" aria-hidden="true" tabindex="-1"></a>                    horizontalalignment<span class="op">=</span><span class="st">&#39;center&#39;</span>, fontsize<span class="op">=</span><span class="dv">13</span>)</span>
<span id="cb68-59"><a href="travel-and-accomodation.html#cb68-59" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb68-60"><a href="travel-and-accomodation.html#cb68-60" aria-hidden="true" tabindex="-1"></a>        plt.show()</span>
<span id="cb68-61"><a href="travel-and-accomodation.html#cb68-61" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb68-62"><a href="travel-and-accomodation.html#cb68-62" aria-hidden="true" tabindex="-1"></a>    <span class="cf">except</span>:</span>
<span id="cb68-63"><a href="travel-and-accomodation.html#cb68-63" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="st">&quot;No Particular Topic&quot;</span></span></code></pre></div>
<div class="sourceCode" id="cb69"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb69-1"><a href="travel-and-accomodation.html#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co">#let&#39;s see what they said about staff</span></span>
<span id="cb69-2"><a href="travel-and-accomodation.html#cb69-2" aria-hidden="true" tabindex="-1"></a>plot_network(ngrams_frequency(create_ngrams(example, <span class="dv">3</span>, aspect <span class="op">=</span> <span class="st">&#39;staff&#39;</span>), <span class="dv">25</span>))</span></code></pre></div>
<p><img src="bookmlindustry_files/figure-html/unnamed-chunk-3-15.png" width="960" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb70"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb70-1"><a href="travel-and-accomodation.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># How about breakfast?</span></span>
<span id="cb70-2"><a href="travel-and-accomodation.html#cb70-2" aria-hidden="true" tabindex="-1"></a>plot_network(ngrams_frequency(create_ngrams(example, <span class="dv">4</span>, aspect <span class="op">=</span> <span class="st">&#39;breakfast&#39;</span>), <span class="dv">25</span>))</span></code></pre></div>
<p><img src="bookmlindustry_files/figure-html/unnamed-chunk-3-17.png" width="960" style="display: block; margin: auto;" /></p>
<p>Kita telah mendapatkan aspek-aspek yang akan kita jadikan variabel penilaian terkait hotel di dataset ini yang telah disimpan di dalam variabel <strong>aspects</strong>. Berdasarkan aspek-aspek tersebut, dilakukan sentimen analisis untuk menilai seberapa baik fasilitas dan pelayanan hotel berdasarkan review yang disajikan dalam sebuah nilai. Hasil dari sentiment analysis memiliki rentang -1 (paling buruk) sampai 1 (paling baik) yang nantinya dinormalisasi dalam rentang 0 - 10.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb71-1"><a href="travel-and-accomodation.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># let&#39;s do sentiment analysis for each aspects of each hotels</span></span>
<span id="cb71-2"><a href="travel-and-accomodation.html#cb71-2" aria-hidden="true" tabindex="-1"></a>aspects</span></code></pre></div>
<pre><code>#&gt; [&#39;staff&#39;, &#39;room&#39;, &#39;breakfast&#39;, &#39;service&#39;, &#39;view&#39;, &#39;restaurant&#39;, &#39;bathroom&#39;, &#39;pool&#39;]</code></pre>
<p>Sebelum melakukan analisis sentimen, kolom <em>Negative Review</em> dan <em>Positive Review</em> digabungkan agar tidak terjadi bias dalam penilaian. Selanjutnya untuk setiap aspek dimuat dalam <strong>ngrams</strong> dengan n = 3 (biasa disebut <em>trigrams</em>). Hasil dari <em>trigrams</em> ini digabungkan (diratakan dengan metode <em>flatten</em>) sehingga didapat satu dokumen baru yang hanya membahas aspek tersebut. Satu dokumen tersebut dihitung skor sentimennya berdasarkan <em>polarity</em> atau ekspresi sentimen dari wisatawan terkait aspek tersebut.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb73-1"><a href="travel-and-accomodation.html#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine the review</span></span>
<span id="cb73-2"><a href="travel-and-accomodation.html#cb73-2" aria-hidden="true" tabindex="-1"></a>df_reviews[<span class="st">&#39;Review&#39;</span>] <span class="op">=</span> df_reviews[<span class="st">&#39;Negative_Review&#39;</span>] <span class="op">+</span> df_reviews[<span class="st">&#39;Positive_Review&#39;</span>]</span>
<span id="cb73-3"><a href="travel-and-accomodation.html#cb73-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-4"><a href="travel-and-accomodation.html#cb73-4" aria-hidden="true" tabindex="-1"></a><span class="co">#plot_network(ngrams_frequency(create_ngrams(example, 3, aspect = &#39;staff&#39;), 25))</span></span>
<span id="cb73-5"><a href="travel-and-accomodation.html#cb73-5" aria-hidden="true" tabindex="-1"></a><span class="co"># extract each ngrams from each Hotel Reviews based on aspects</span></span>
<span id="cb73-6"><a href="travel-and-accomodation.html#cb73-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tqdm <span class="im">import</span> tqdm</span>
<span id="cb73-7"><a href="travel-and-accomodation.html#cb73-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-8"><a href="travel-and-accomodation.html#cb73-8" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">3</span></span>
<span id="cb73-9"><a href="travel-and-accomodation.html#cb73-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> aspect <span class="kw">in</span> tqdm(aspects):</span>
<span id="cb73-10"><a href="travel-and-accomodation.html#cb73-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># create empty list to store sentiment score</span></span>
<span id="cb73-11"><a href="travel-and-accomodation.html#cb73-11" aria-hidden="true" tabindex="-1"></a>    sent_list <span class="op">=</span> []</span>
<span id="cb73-12"><a href="travel-and-accomodation.html#cb73-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> df_reviews[<span class="st">&#39;Review&#39;</span>]:</span>
<span id="cb73-13"><a href="travel-and-accomodation.html#cb73-13" aria-hidden="true" tabindex="-1"></a>        <span class="co"># create ngrams</span></span>
<span id="cb73-14"><a href="travel-and-accomodation.html#cb73-14" aria-hidden="true" tabindex="-1"></a>        ngram_i <span class="op">=</span> create_ngrams(i, n, aspect <span class="op">=</span> aspect)</span>
<span id="cb73-15"><a href="travel-and-accomodation.html#cb73-15" aria-hidden="true" tabindex="-1"></a>        <span class="co"># flatten ngrams to make clean list</span></span>
<span id="cb73-16"><a href="travel-and-accomodation.html#cb73-16" aria-hidden="true" tabindex="-1"></a>        ngram_flatten_i <span class="op">=</span> ngrams_flatten(ngram_i)</span>
<span id="cb73-17"><a href="travel-and-accomodation.html#cb73-17" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Get polarity</span></span>
<span id="cb73-18"><a href="travel-and-accomodation.html#cb73-18" aria-hidden="true" tabindex="-1"></a>        polarity_i <span class="op">=</span> getPolarity(<span class="st">&#39; &#39;</span>.join(ngram_flatten_i))</span>
<span id="cb73-19"><a href="travel-and-accomodation.html#cb73-19" aria-hidden="true" tabindex="-1"></a>        sent_list.append(polarity_i)</span>
<span id="cb73-20"><a href="travel-and-accomodation.html#cb73-20" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb73-21"><a href="travel-and-accomodation.html#cb73-21" aria-hidden="true" tabindex="-1"></a>    df_reviews[aspect] <span class="op">=</span> sent_list</span></code></pre></div>
<pre><code>#&gt; 
  0%|          | 0/8 [00:00&lt;?, ?it/s]
 12%|#2        | 1/8 [00:11&lt;01:21, 11.71s/it]
 25%|##5       | 2/8 [00:31&lt;01:37, 16.29s/it]
 38%|###7      | 3/8 [00:38&lt;01:01, 12.36s/it]
 50%|#####     | 4/8 [00:42&lt;00:35,  8.86s/it]
 62%|######2   | 5/8 [00:45&lt;00:20,  6.71s/it]
 75%|#######5  | 6/8 [00:48&lt;00:10,  5.47s/it]
 88%|########7 | 7/8 [00:51&lt;00:04,  4.84s/it]
100%|##########| 8/8 [00:54&lt;00:00,  3.99s/it]
100%|##########| 8/8 [00:54&lt;00:00,  6.76s/it]</code></pre>
<p>Sehingga didapat nilai untuk masing-masing aspek untuk setiap hotel yang dimuat pada dataframe berikut.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb75-1"><a href="travel-and-accomodation.html#cb75-1" aria-hidden="true" tabindex="-1"></a>df_reviews.head(<span class="dv">2</span>)</span></code></pre></div>
<pre><code>#&gt;                                                       Negative_Review  \
#&gt; Hotel_Name                                                              
#&gt; 11 Cadogan Gardens  [thought, prise, drink, little, excessive, not...   
#&gt; 1K Hotel            [conditioning, room, work, despite, complainin...   
#&gt; 
#&gt;                                                       Positive_Review  \
#&gt; Hotel_Name                                                              
#&gt; 11 Cadogan Gardens  [particularly, impressed, warm, welcome, recei...   
#&gt; 1K Hotel            [location, good, close, marais, arrondissement...   
#&gt; 
#&gt;                                                                Review  \
#&gt; Hotel_Name                                                              
#&gt; 11 Cadogan Gardens  [thought, prise, drink, little, excessive, not...   
#&gt; 1K Hotel            [conditioning, room, work, despite, complainin...   
#&gt; 
#&gt;                        staff      room  breakfast   service      view  \
#&gt; Hotel_Name                                                              
#&gt; 11 Cadogan Gardens  0.502761  0.202778   0.119945  0.484459  0.177778   
#&gt; 1K Hotel            0.421448  0.286418   0.104862  0.162868 -0.093750   
#&gt; 
#&gt;                     restaurant  bathroom  pool  
#&gt; Hotel_Name                                      
#&gt; 11 Cadogan Gardens    0.465476  0.018318   0.0  
#&gt; 1K Hotel              0.448333  0.332811   0.0</code></pre>
<p>Perlu diperhatikan bahwa nilai sentimen masih berupa nilai dalam rentang -1 hingga 1. Untuk mempermudah pemilihan hotel, alangkah lebih baik nilai sentimen dinormalisasi menjadi skor dengan rentang 0 - 10.</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb77-1"><a href="travel-and-accomodation.html#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Normalize sentiment in range of 0 - 10</span></span>
<span id="cb77-2"><a href="travel-and-accomodation.html#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> normalizeSentiment(x):</span>
<span id="cb77-3"><a href="travel-and-accomodation.html#cb77-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">max</span>(x) <span class="op">&lt;=</span> <span class="dv">1</span>:</span>
<span id="cb77-4"><a href="travel-and-accomodation.html#cb77-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> (x<span class="op">-</span>(<span class="op">-</span><span class="dv">1</span>))<span class="op">/</span>(<span class="dv">1</span><span class="op">+</span><span class="dv">1</span>)<span class="op">*</span><span class="dv">10</span></span>
<span id="cb77-5"><a href="travel-and-accomodation.html#cb77-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb77-6"><a href="travel-and-accomodation.html#cb77-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> (x)</span>
<span id="cb77-7"><a href="travel-and-accomodation.html#cb77-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-8"><a href="travel-and-accomodation.html#cb77-8" aria-hidden="true" tabindex="-1"></a>df_reviews[aspects] <span class="op">=</span> df_reviews[aspects].<span class="bu">apply</span>(normalizeSentiment)</span>
<span id="cb77-9"><a href="travel-and-accomodation.html#cb77-9" aria-hidden="true" tabindex="-1"></a>df_reviews.head(<span class="dv">2</span>)</span></code></pre></div>
<pre><code>#&gt;                                                       Negative_Review  \
#&gt; Hotel_Name                                                              
#&gt; 11 Cadogan Gardens  [thought, prise, drink, little, excessive, not...   
#&gt; 1K Hotel            [conditioning, room, work, despite, complainin...   
#&gt; 
#&gt;                                                       Positive_Review  \
#&gt; Hotel_Name                                                              
#&gt; 11 Cadogan Gardens  [particularly, impressed, warm, welcome, recei...   
#&gt; 1K Hotel            [location, good, close, marais, arrondissement...   
#&gt; 
#&gt;                                                                Review  \
#&gt; Hotel_Name                                                              
#&gt; 11 Cadogan Gardens  [thought, prise, drink, little, excessive, not...   
#&gt; 1K Hotel            [conditioning, room, work, despite, complainin...   
#&gt; 
#&gt;                        staff      room  breakfast   service      view  \
#&gt; Hotel_Name                                                              
#&gt; 11 Cadogan Gardens  7.513805  6.013889   5.599727  7.422297  5.888889   
#&gt; 1K Hotel            7.107240  6.432088   5.524312  5.814342  4.531250   
#&gt; 
#&gt;                     restaurant  bathroom  pool  
#&gt; Hotel_Name                                      
#&gt; 11 Cadogan Gardens    7.327381  5.091588   5.0  
#&gt; 1K Hotel              7.241667  6.664053   5.0</code></pre>
<p>Gabungkan kolom-kolom yang memuat informasi tambahan yang dibutuhkan ke dataframe.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb79-1"><a href="travel-and-accomodation.html#cb79-1" aria-hidden="true" tabindex="-1"></a>col_df <span class="op">=</span> [<span class="st">&#39;Average_Score&#39;</span>, <span class="st">&#39;Total_Number_of_Reviews&#39;</span>,<span class="st">&#39;Hotel_Name&#39;</span>, <span class="st">&#39;Hotel_Address&#39;</span>,<span class="st">&#39;lat&#39;</span>,<span class="st">&#39;lng&#39;</span>]</span>
<span id="cb79-2"><a href="travel-and-accomodation.html#cb79-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-3"><a href="travel-and-accomodation.html#cb79-3" aria-hidden="true" tabindex="-1"></a>df_merge <span class="op">=</span> pd.merge(df_reviews, df[col_df].drop_duplicates(), how <span class="op">=</span> <span class="st">&#39;left&#39;</span>, on <span class="op">=</span> <span class="st">&#39;Hotel_Name&#39;</span>)</span>
<span id="cb79-4"><a href="travel-and-accomodation.html#cb79-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-5"><a href="travel-and-accomodation.html#cb79-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-6"><a href="travel-and-accomodation.html#cb79-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> join_list(my_list):</span>
<span id="cb79-7"><a href="travel-and-accomodation.html#cb79-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="st">&quot; &quot;</span>.join(my_list)</span>
<span id="cb79-8"><a href="travel-and-accomodation.html#cb79-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-9"><a href="travel-and-accomodation.html#cb79-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-10"><a href="travel-and-accomodation.html#cb79-10" aria-hidden="true" tabindex="-1"></a>df_merge[<span class="st">&#39;Review&#39;</span>] <span class="op">=</span> df_merge[<span class="st">&#39;Review&#39;</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: join_list(x))</span>
<span id="cb79-11"><a href="travel-and-accomodation.html#cb79-11" aria-hidden="true" tabindex="-1"></a>df_merge[<span class="st">&#39;Negative_Review&#39;</span>] <span class="op">=</span> df_merge[<span class="st">&#39;Negative_Review&#39;</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: join_list(x))</span>
<span id="cb79-12"><a href="travel-and-accomodation.html#cb79-12" aria-hidden="true" tabindex="-1"></a>df_merge[<span class="st">&#39;Positive_Review&#39;</span>] <span class="op">=</span> df_merge[<span class="st">&#39;Positive_Review&#39;</span>].<span class="bu">apply</span>(<span class="kw">lambda</span> x: join_list(x))</span>
<span id="cb79-13"><a href="travel-and-accomodation.html#cb79-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-14"><a href="travel-and-accomodation.html#cb79-14" aria-hidden="true" tabindex="-1"></a>df_merge.head(<span class="dv">3</span>)</span></code></pre></div>
<pre><code>#&gt;                            Hotel_Name  \
#&gt; 0                  11 Cadogan Gardens   
#&gt; 1                            1K Hotel   
#&gt; 2  25hours Hotel beim MuseumsQuartier   
#&gt; 
#&gt;                                      Negative_Review  \
#&gt; 0  thought prise drink little excessive nothing p...   
#&gt; 1  conditioning room work despite complaining fix...   
#&gt; 2  breakfast included buffet really expensive bre...   
#&gt; 
#&gt;                                      Positive_Review  \
#&gt; 0  particularly impressed warm welcome received l...   
#&gt; 1  location good close marais arrondissement fitn...   
#&gt; 2  cool vintage style middle museum quarter metro...   
#&gt; 
#&gt;                                               Review     staff      room  \
#&gt; 0  thought prise drink little excessive nothing p...  7.513805  6.013889   
#&gt; 1  conditioning room work despite complaining fix...  7.107240  6.432088   
#&gt; 2  breakfast included buffet really expensive bre...  7.261356  6.139688   
#&gt; 
#&gt;    breakfast   service      view  restaurant  bathroom  pool  Average_Score  \
#&gt; 0   5.599727  7.422297  5.888889    7.327381  5.091588   5.0            8.7   
#&gt; 1   5.524312  5.814342  4.531250    7.241667  6.664053   5.0            7.7   
#&gt; 2   7.106359  6.979958  7.849841    7.266420  6.738946   5.0            8.8   
#&gt; 
#&gt;    Total_Number_of_Reviews                                      Hotel_Address  \
#&gt; 0                      393  11 Cadogan Gardens Sloane Square Kensington an...   
#&gt; 1                      663  13 Boulevard Du Temple 3rd arr 75003 Paris France   
#&gt; 2                     4324  Lerchenfelder Stra e 1 3 07 Neubau 1070 Vienna...   
#&gt; 
#&gt;          lat        lng  
#&gt; 0  51.493616  -0.159235  
#&gt; 1  48.863932   2.365874  
#&gt; 2  48.206474  16.354630</code></pre>
</div>
<div id="dashboard-ideas" class="section level3" number="9.1.4">
<h3><span class="header-section-number">9.1.4</span> Dashboard Ideas</h3>
<p>Salah satu cara terbaik untuk memberikan informasi adalah melalui <em>dashboard</em> interaktif yang dapat dioperasikan langsung oleh penggunanya. Tentunya kemudahan yang diberikan akan meningkatkan penyerapan informasi oleh pengguna. berikut adalah beberapa ide-ide fitur yang akan dimuat di dalam dashboard tersebut.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb81-1"><a href="travel-and-accomodation.html#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function for dashboard</span></span>
<span id="cb81-2"><a href="travel-and-accomodation.html#cb81-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-3"><a href="travel-and-accomodation.html#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> radar_plot(data): <span class="co"># data categories must be stored as index</span></span>
<span id="cb81-4"><a href="travel-and-accomodation.html#cb81-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-5"><a href="travel-and-accomodation.html#cb81-5" aria-hidden="true" tabindex="-1"></a>    plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">10</span>))</span>
<span id="cb81-6"><a href="travel-and-accomodation.html#cb81-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># number of variable</span></span>
<span id="cb81-7"><a href="travel-and-accomodation.html#cb81-7" aria-hidden="true" tabindex="-1"></a>    categories<span class="op">=</span>s.index</span>
<span id="cb81-8"><a href="travel-and-accomodation.html#cb81-8" aria-hidden="true" tabindex="-1"></a>    N <span class="op">=</span> <span class="bu">len</span>(s)</span>
<span id="cb81-9"><a href="travel-and-accomodation.html#cb81-9" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb81-10"><a href="travel-and-accomodation.html#cb81-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># We are going to plot the first line of the data frame.</span></span>
<span id="cb81-11"><a href="travel-and-accomodation.html#cb81-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># But we need to repeat the first value to close the circular graph:</span></span>
<span id="cb81-12"><a href="travel-and-accomodation.html#cb81-12" aria-hidden="true" tabindex="-1"></a>    values<span class="op">=</span> s.iloc[:,<span class="dv">0</span>].values.flatten().tolist()</span>
<span id="cb81-13"><a href="travel-and-accomodation.html#cb81-13" aria-hidden="true" tabindex="-1"></a>    values <span class="op">+=</span> values[:<span class="dv">1</span>]</span>
<span id="cb81-14"><a href="travel-and-accomodation.html#cb81-14" aria-hidden="true" tabindex="-1"></a>    values</span>
<span id="cb81-15"><a href="travel-and-accomodation.html#cb81-15" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb81-16"><a href="travel-and-accomodation.html#cb81-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># What will be the angle of each axis in the plot? (we divide the plot / number of variable)</span></span>
<span id="cb81-17"><a href="travel-and-accomodation.html#cb81-17" aria-hidden="true" tabindex="-1"></a>    angles <span class="op">=</span> [n <span class="op">/</span> <span class="bu">float</span>(N) <span class="op">*</span> <span class="dv">2</span> <span class="op">*</span> pi <span class="cf">for</span> n <span class="kw">in</span> <span class="bu">range</span>(N)]</span>
<span id="cb81-18"><a href="travel-and-accomodation.html#cb81-18" aria-hidden="true" tabindex="-1"></a>    angles <span class="op">+=</span> angles[:<span class="dv">1</span>]</span>
<span id="cb81-19"><a href="travel-and-accomodation.html#cb81-19" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb81-20"><a href="travel-and-accomodation.html#cb81-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Initialise the spider plot</span></span>
<span id="cb81-21"><a href="travel-and-accomodation.html#cb81-21" aria-hidden="true" tabindex="-1"></a>    ax <span class="op">=</span> plt.subplot(<span class="dv">111</span>, polar<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb81-22"><a href="travel-and-accomodation.html#cb81-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-23"><a href="travel-and-accomodation.html#cb81-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Draw one axe per variable + add labels labels yet</span></span>
<span id="cb81-24"><a href="travel-and-accomodation.html#cb81-24" aria-hidden="true" tabindex="-1"></a>    plt.xticks(angles[:<span class="op">-</span><span class="dv">1</span>], categories, color<span class="op">=</span><span class="st">&#39;blue&#39;</span>, size<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb81-25"><a href="travel-and-accomodation.html#cb81-25" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb81-26"><a href="travel-and-accomodation.html#cb81-26" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Draw ylabels</span></span>
<span id="cb81-27"><a href="travel-and-accomodation.html#cb81-27" aria-hidden="true" tabindex="-1"></a>    ax.set_rlabel_position(<span class="dv">90</span>)</span>
<span id="cb81-28"><a href="travel-and-accomodation.html#cb81-28" aria-hidden="true" tabindex="-1"></a>    plt.yticks([<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">8</span>], [<span class="st">&quot;2&quot;</span>,<span class="st">&quot;4&quot;</span>,<span class="st">&quot;6&quot;</span>,<span class="st">&quot;8&quot;</span>], color<span class="op">=</span><span class="st">&quot;grey&quot;</span>, size<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb81-29"><a href="travel-and-accomodation.html#cb81-29" aria-hidden="true" tabindex="-1"></a>    plt.ylim(<span class="dv">0</span>,<span class="dv">10</span>)</span>
<span id="cb81-30"><a href="travel-and-accomodation.html#cb81-30" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb81-31"><a href="travel-and-accomodation.html#cb81-31" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Plot data</span></span>
<span id="cb81-32"><a href="travel-and-accomodation.html#cb81-32" aria-hidden="true" tabindex="-1"></a>    ax.plot(angles, values, linewidth<span class="op">=</span><span class="dv">2</span>, linestyle<span class="op">=</span><span class="st">&#39;solid&#39;</span>)</span>
<span id="cb81-33"><a href="travel-and-accomodation.html#cb81-33" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb81-34"><a href="travel-and-accomodation.html#cb81-34" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Fill area</span></span>
<span id="cb81-35"><a href="travel-and-accomodation.html#cb81-35" aria-hidden="true" tabindex="-1"></a>    ax.fill(angles, values, <span class="st">&#39;b&#39;</span>, alpha<span class="op">=</span><span class="fl">0.1</span>)</span>
<span id="cb81-36"><a href="travel-and-accomodation.html#cb81-36" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb81-37"><a href="travel-and-accomodation.html#cb81-37" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_coordinate(lat, lng , name <span class="op">=</span> pd.Series([<span class="st">&#39;&#39;</span>]), address <span class="op">=</span> pd.Series([<span class="st">&#39;&#39;</span>]),  zoom_start <span class="op">=</span> <span class="dv">10</span>, color <span class="op">=</span> <span class="st">&#39;red&#39;</span>, fill_color <span class="op">=</span> <span class="st">&#39;blue&#39;</span>):   </span>
<span id="cb81-38"><a href="travel-and-accomodation.html#cb81-38" aria-hidden="true" tabindex="-1"></a>    m <span class="op">=</span> folium.Map(location<span class="op">=</span>[lat,lng], zoom_start<span class="op">=</span>zoom_start)</span>
<span id="cb81-39"><a href="travel-and-accomodation.html#cb81-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-40"><a href="travel-and-accomodation.html#cb81-40" aria-hidden="true" tabindex="-1"></a>    folium.CircleMarker(</span>
<span id="cb81-41"><a href="travel-and-accomodation.html#cb81-41" aria-hidden="true" tabindex="-1"></a>            [lat.values[<span class="dv">0</span>], lng.values[<span class="dv">0</span>]],</span>
<span id="cb81-42"><a href="travel-and-accomodation.html#cb81-42" aria-hidden="true" tabindex="-1"></a>            radius<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb81-43"><a href="travel-and-accomodation.html#cb81-43" aria-hidden="true" tabindex="-1"></a>            color<span class="op">=</span>color,</span>
<span id="cb81-44"><a href="travel-and-accomodation.html#cb81-44" aria-hidden="true" tabindex="-1"></a>            popup<span class="op">=</span><span class="st">&#39;Name: &#39;</span> <span class="op">+</span> name.values[<span class="dv">0</span>] <span class="op">+</span> <span class="st">&#39;</span><span class="ch">\n\n</span><span class="st"> Address: &#39;</span> <span class="op">+</span> address.values[<span class="dv">0</span>],</span>
<span id="cb81-45"><a href="travel-and-accomodation.html#cb81-45" aria-hidden="true" tabindex="-1"></a>            fill <span class="op">=</span> <span class="va">True</span>,</span>
<span id="cb81-46"><a href="travel-and-accomodation.html#cb81-46" aria-hidden="true" tabindex="-1"></a>            fill_color <span class="op">=</span> fill_color,</span>
<span id="cb81-47"><a href="travel-and-accomodation.html#cb81-47" aria-hidden="true" tabindex="-1"></a>            fill_opacity<span class="op">=</span><span class="fl">0.6</span></span>
<span id="cb81-48"><a href="travel-and-accomodation.html#cb81-48" aria-hidden="true" tabindex="-1"></a>        ).add_to(m)</span>
<span id="cb81-49"><a href="travel-and-accomodation.html#cb81-49" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> m</span></code></pre></div>
<p>Search bar berfungsi untuk melakukan pemenggalan data (<em>querying</em>) untuk mengambil data yang menjadi fokus bagi penggunanya.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb82-1"><a href="travel-and-accomodation.html#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Search Bar</span></span>
<span id="cb82-2"><a href="travel-and-accomodation.html#cb82-2" aria-hidden="true" tabindex="-1"></a>search <span class="op">=</span> <span class="st">&#39;25hours Hotel beim MuseumsQuartier&#39;</span></span>
<span id="cb82-3"><a href="travel-and-accomodation.html#cb82-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-4"><a href="travel-and-accomodation.html#cb82-4" aria-hidden="true" tabindex="-1"></a>search_data <span class="op">=</span> df_merge[df_merge[<span class="st">&#39;Hotel_Name&#39;</span>] <span class="op">==</span> search]</span>
<span id="cb82-5"><a href="travel-and-accomodation.html#cb82-5" aria-hidden="true" tabindex="-1"></a>search_data</span></code></pre></div>
<pre><code>#&gt;                            Hotel_Name  \
#&gt; 2  25hours Hotel beim MuseumsQuartier   
#&gt; 
#&gt;                                      Negative_Review  \
#&gt; 2  breakfast included buffet really expensive bre...   
#&gt; 
#&gt;                                      Positive_Review  \
#&gt; 2  cool vintage style middle museum quarter metro...   
#&gt; 
#&gt;                                               Review     staff      room  \
#&gt; 2  breakfast included buffet really expensive bre...  7.261356  6.139688   
#&gt; 
#&gt;    breakfast   service      view  restaurant  bathroom  pool  Average_Score  \
#&gt; 2   7.106359  6.979958  7.849841     7.26642  6.738946   5.0            8.8   
#&gt; 
#&gt;    Total_Number_of_Reviews                                      Hotel_Address  \
#&gt; 2                     4324  Lerchenfelder Stra e 1 3 07 Neubau 1070 Vienna...   
#&gt; 
#&gt;          lat       lng  
#&gt; 2  48.206474  16.35463</code></pre>
<p>Average score menampilkan rating rata-rata yang diberikan oleh wisatawan terdahulu terhadap pengalaman singgah di hotel tersebut.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb84-1"><a href="travel-and-accomodation.html#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Average Score</span></span>
<span id="cb84-2"><a href="travel-and-accomodation.html#cb84-2" aria-hidden="true" tabindex="-1"></a>search_data[<span class="st">&#39;Average_Score&#39;</span>].values[<span class="dv">0</span>]</span></code></pre></div>
<pre><code>#&gt; 8.8</code></pre>
<p>Jumlah orang yang memberikan ulasan juga perlu ditampilkan. Semakin banyak ulasan, semakin <em>reliable</em> penilaian tersebut.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb86-1"><a href="travel-and-accomodation.html#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Total Number of Reviews</span></span>
<span id="cb86-2"><a href="travel-and-accomodation.html#cb86-2" aria-hidden="true" tabindex="-1"></a>search_data[<span class="st">&#39;Total_Number_of_Reviews&#39;</span>].values[<span class="dv">0</span>]</span></code></pre></div>
<pre><code>#&gt; 4324</code></pre>
<p>Titik koordinat diperlukan untuk menyampaikan informasi mengenai lokasi dari hotel tersebut. Hal ini juga bertujuan untuk memberikan informasi mengenai kondisi di sekitar hotel terkait seberapa strategis lokasi hotel tersebut (dekat dengan pusat wisata, pusat pembelanjaan, dan lain-lain).</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb88-1"><a href="travel-and-accomodation.html#cb88-1" aria-hidden="true" tabindex="-1"></a>plot_coordinate(search_data.lat, search_data.lng, search_data.Hotel_Name, search_data.Hotel_Address, zoom_start <span class="op">=</span> <span class="dv">15</span>)</span></code></pre></div>
<div style="width:100%;"><div style="position:relative;width:100%;height:0;padding-bottom:60%;"><span style="color:#565656">Make this Notebook Trusted to load map: File -> Trust Notebook</span><iframe src="about:blank" style="position:absolute;width:100%;height:100%;left:0;top:0;border:none !important;" data-html=%3C%21DOCTYPE%20html%3E%0A%3Chead%3E%20%20%20%20%0A%20%20%20%20%3Cmeta%20http-equiv%3D%22content-type%22%20content%3D%22text/html%3B%20charset%3DUTF-8%22%20/%3E%0A%20%20%20%20%0A%20%20%20%20%20%20%20%20%3Cscript%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20L_NO_TOUCH%20%3D%20false%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20L_DISABLE_3D%20%3D%20false%3B%0A%20%20%20%20%20%20%20%20%3C/script%3E%0A%20%20%20%20%0A%20%20%20%20%3Cstyle%3Ehtml%2C%20body%20%7Bwidth%3A%20100%25%3Bheight%3A%20100%25%3Bmargin%3A%200%3Bpadding%3A%200%3B%7D%3C/style%3E%0A%20%20%20%20%3Cstyle%3E%23map%20%7Bposition%3Aabsolute%3Btop%3A0%3Bbottom%3A0%3Bright%3A0%3Bleft%3A0%3B%7D%3C/style%3E%0A%20%20%20%20%3Cscript%20src%3D%22https%3A//cdn.jsdelivr.net/npm/leaflet%401.6.0/dist/leaflet.js%22%3E%3C/script%3E%0A%20%20%20%20%3Cscript%20src%3D%22https%3A//code.jquery.com/jquery-1.12.4.min.js%22%3E%3C/script%3E%0A%20%20%20%20%3Cscript%20src%3D%22https%3A//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js%22%3E%3C/script%3E%0A%20%20%20%20%3Cscript%20src%3D%22https%3A//cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.js%22%3E%3C/script%3E%0A%20%20%20%20%3Clink%20rel%3D%22stylesheet%22%20href%3D%22https%3A//cdn.jsdelivr.net/npm/leaflet%401.6.0/dist/leaflet.css%22/%3E%0A%20%20%20%20%3Clink%20rel%3D%22stylesheet%22%20href%3D%22https%3A//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css%22/%3E%0A%20%20%20%20%3Clink%20rel%3D%22stylesheet%22%20href%3D%22https%3A//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css%22/%3E%0A%20%20%20%20%3Clink%20rel%3D%22stylesheet%22%20href%3D%22https%3A//maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css%22/%3E%0A%20%20%20%20%3Clink%20rel%3D%22stylesheet%22%20href%3D%22https%3A//cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.css%22/%3E%0A%20%20%20%20%3Clink%20rel%3D%22stylesheet%22%20href%3D%22https%3A//cdn.jsdelivr.net/gh/python-visualization/folium/folium/templates/leaflet.awesome.rotate.min.css%22/%3E%0A%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cmeta%20name%3D%22viewport%22%20content%3D%22width%3Ddevice-width%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20initial-scale%3D1.0%2C%20maximum-scale%3D1.0%2C%20user-scalable%3Dno%22%20/%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cstyle%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%23map_7686206813e94acda4d4e5b417bef293%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20position%3A%20relative%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20width%3A%20100.0%25%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20height%3A%20100.0%25%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20left%3A%200.0%25%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20top%3A%200.0%25%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%3C/style%3E%0A%20%20%20%20%20%20%20%20%0A%3C/head%3E%0A%3Cbody%3E%20%20%20%20%0A%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%3Cdiv%20class%3D%22folium-map%22%20id%3D%22map_7686206813e94acda4d4e5b417bef293%22%20%3E%3C/div%3E%0A%20%20%20%20%20%20%20%20%0A%3C/body%3E%0A%3Cscript%3E%20%20%20%20%0A%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20var%20map_7686206813e94acda4d4e5b417bef293%20%3D%20L.map%28%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22map_7686206813e94acda4d4e5b417bef293%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20center%3A%20%5B48.2064745%2C%2016.3546297%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20crs%3A%20L.CRS.EPSG3857%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20zoom%3A%2015%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20zoomControl%3A%20true%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20preferCanvas%3A%20false%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%29%3B%0A%0A%20%20%20%20%20%20%20%20%20%20%20%20%0A%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20var%20tile_layer_c2203a169dfc4b3a9d60bc2b625d4ef8%20%3D%20L.tileLayer%28%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22https%3A//%7Bs%7D.tile.openstreetmap.org/%7Bz%7D/%7Bx%7D/%7By%7D.png%22%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%22attribution%22%3A%20%22Data%20by%20%5Cu0026copy%3B%20%5Cu003ca%20href%3D%5C%22http%3A//openstreetmap.org%5C%22%5Cu003eOpenStreetMap%5Cu003c/a%5Cu003e%2C%20under%20%5Cu003ca%20href%3D%5C%22http%3A//www.openstreetmap.org/copyright%5C%22%5Cu003eODbL%5Cu003c/a%5Cu003e.%22%2C%20%22detectRetina%22%3A%20false%2C%20%22maxNativeZoom%22%3A%2018%2C%20%22maxZoom%22%3A%2018%2C%20%22minZoom%22%3A%200%2C%20%22noWrap%22%3A%20false%2C%20%22opacity%22%3A%201%2C%20%22subdomains%22%3A%20%22abc%22%2C%20%22tms%22%3A%20false%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%29.addTo%28map_7686206813e94acda4d4e5b417bef293%29%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20var%20circle_marker_6e2794a8ee614e81a565f697570c4585%20%3D%20L.circleMarker%28%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5B48.2064745%2C%2016.3546297%5D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%22bubblingMouseEvents%22%3A%20true%2C%20%22color%22%3A%20%22red%22%2C%20%22dashArray%22%3A%20null%2C%20%22dashOffset%22%3A%20null%2C%20%22fill%22%3A%20true%2C%20%22fillColor%22%3A%20%22blue%22%2C%20%22fillOpacity%22%3A%200.6%2C%20%22fillRule%22%3A%20%22evenodd%22%2C%20%22lineCap%22%3A%20%22round%22%2C%20%22lineJoin%22%3A%20%22round%22%2C%20%22opacity%22%3A%201.0%2C%20%22radius%22%3A%2010%2C%20%22stroke%22%3A%20true%2C%20%22weight%22%3A%203%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%29.addTo%28map_7686206813e94acda4d4e5b417bef293%29%3B%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%0A%20%20%20%20%20%20%20%20var%20popup_b16ae620dcd14e0b906b26b14581f4ea%20%3D%20L.popup%28%7B%22maxWidth%22%3A%20%22100%25%22%7D%29%3B%0A%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%20%20%20%20var%20html_f67b30d94d4146d5b7af1b1790affa3b%20%3D%20%24%28%60%3Cdiv%20id%3D%22html_f67b30d94d4146d5b7af1b1790affa3b%22%20style%3D%22width%3A%20100.0%25%3B%20height%3A%20100.0%25%3B%22%3EName%3A%2025hours%20Hotel%20beim%20MuseumsQuartier%20%20%20Address%3A%20Lerchenfelder%20Stra%20e%201%203%2007%20Neubau%201070%20Vienna%20Austria%3C/div%3E%60%29%5B0%5D%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20popup_b16ae620dcd14e0b906b26b14581f4ea.setContent%28html_f67b30d94d4146d5b7af1b1790affa3b%29%3B%0A%20%20%20%20%20%20%20%20%0A%0A%20%20%20%20%20%20%20%20circle_marker_6e2794a8ee614e81a565f697570c4585.bindPopup%28popup_b16ae620dcd14e0b906b26b14581f4ea%29%0A%20%20%20%20%20%20%20%20%3B%0A%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%0A%3C/script%3E onload="this.contentDocument.open();this.contentDocument.write(    decodeURIComponent(this.getAttribute('data-html')));this.contentDocument.close();" allowfullscreen webkitallowfullscreen mozallowfullscreen></iframe></div></div>
<p>Hasil dari analisis sentimen terkait aspek (fasilitas dan pelayanan) hotel dimuat dalam bentuk visualisasi <em>radar plot</em> untuk mempermudah pengambilan keputusan dalam memilih hotel yang akan dijadikan tempat singgah sementara.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb89-1"><a href="travel-and-accomodation.html#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sentiment Score</span></span>
<span id="cb89-2"><a href="travel-and-accomodation.html#cb89-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-3"><a href="travel-and-accomodation.html#cb89-3" aria-hidden="true" tabindex="-1"></a>s <span class="op">=</span> search_data[aspects].T</span>
<span id="cb89-4"><a href="travel-and-accomodation.html#cb89-4" aria-hidden="true" tabindex="-1"></a>radar_plot(s)</span></code></pre></div>
<p>Diagram jaringan (<em>network diagram</em>) untuk melihat korelasi kata-kata dengan aspek yang dipilih.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb90-1"><a href="travel-and-accomodation.html#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co">#let&#39;s see what they said about staff</span></span>
<span id="cb90-2"><a href="travel-and-accomodation.html#cb90-2" aria-hidden="true" tabindex="-1"></a>plot_network(ngrams_frequency(create_ngrams(search_data[<span class="st">&#39;Review&#39;</span>].values[<span class="dv">0</span>].split(), <span class="dv">3</span>, aspect <span class="op">=</span> <span class="st">&#39;staff&#39;</span>), <span class="dv">20</span>))</span></code></pre></div>
<p><img src="bookmlindustry_files/figure-html/unnamed-chunk-3-19.png" width="960" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb91"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb91-1"><a href="travel-and-accomodation.html#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co">#let&#39;s see what they said about room</span></span>
<span id="cb91-2"><a href="travel-and-accomodation.html#cb91-2" aria-hidden="true" tabindex="-1"></a>plot_network(ngrams_frequency(create_ngrams(search_data[<span class="st">&#39;Review&#39;</span>].values[<span class="dv">0</span>].split(), <span class="dv">3</span>, aspect <span class="op">=</span> <span class="st">&#39;room&#39;</span>), <span class="dv">20</span>))</span></code></pre></div>
<p><img src="bookmlindustry_files/figure-html/unnamed-chunk-3-21.png" width="960" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb92"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb92-1"><a href="travel-and-accomodation.html#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co">#let&#39;s see what they said about breakfast</span></span>
<span id="cb92-2"><a href="travel-and-accomodation.html#cb92-2" aria-hidden="true" tabindex="-1"></a>plot_network(ngrams_frequency(create_ngrams(search_data[<span class="st">&#39;Review&#39;</span>].values[<span class="dv">0</span>].split(), <span class="dv">3</span>, aspect <span class="op">=</span> <span class="st">&#39;breakfast&#39;</span>), <span class="dv">20</span>))</span></code></pre></div>
<p><img src="bookmlindustry_files/figure-html/unnamed-chunk-3-23.png" width="960" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb93"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb93-1"><a href="travel-and-accomodation.html#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co">#let&#39;s see what they said about service</span></span>
<span id="cb93-2"><a href="travel-and-accomodation.html#cb93-2" aria-hidden="true" tabindex="-1"></a>plot_network(ngrams_frequency(create_ngrams(search_data[<span class="st">&#39;Review&#39;</span>].values[<span class="dv">0</span>].split(), <span class="dv">3</span>, aspect <span class="op">=</span> <span class="st">&#39;service&#39;</span>), <span class="dv">20</span>))</span></code></pre></div>
<p><img src="bookmlindustry_files/figure-html/unnamed-chunk-3-25.png" width="960" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb94"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb94-1"><a href="travel-and-accomodation.html#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co">#let&#39;s see what they said about view</span></span>
<span id="cb94-2"><a href="travel-and-accomodation.html#cb94-2" aria-hidden="true" tabindex="-1"></a>plot_network(ngrams_frequency(create_ngrams(search_data[<span class="st">&#39;Review&#39;</span>].values[<span class="dv">0</span>].split(), <span class="dv">3</span>, aspect <span class="op">=</span> <span class="st">&#39;view&#39;</span>), <span class="dv">20</span>))</span></code></pre></div>
<p><img src="bookmlindustry_files/figure-html/unnamed-chunk-3-27.png" width="960" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb95"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb95-1"><a href="travel-and-accomodation.html#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co">#let&#39;s see what they said about restaurant</span></span>
<span id="cb95-2"><a href="travel-and-accomodation.html#cb95-2" aria-hidden="true" tabindex="-1"></a>plot_network(ngrams_frequency(create_ngrams(search_data[<span class="st">&#39;Review&#39;</span>].values[<span class="dv">0</span>].split(), <span class="dv">3</span>, aspect <span class="op">=</span> <span class="st">&#39;restaurant&#39;</span>), <span class="dv">20</span>))</span></code></pre></div>
<p><img src="bookmlindustry_files/figure-html/unnamed-chunk-3-29.png" width="960" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb96"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb96-1"><a href="travel-and-accomodation.html#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co">#let&#39;s see what they said about pool</span></span>
<span id="cb96-2"><a href="travel-and-accomodation.html#cb96-2" aria-hidden="true" tabindex="-1"></a>plot_network(ngrams_frequency(create_ngrams(search_data[<span class="st">&#39;Review&#39;</span>].values[<span class="dv">0</span>].split(), <span class="dv">3</span>, aspect <span class="op">=</span> <span class="st">&#39;pool&#39;</span>), <span class="dv">20</span>))</span></code></pre></div>
<p><img src="bookmlindustry_files/figure-html/unnamed-chunk-3-31.png" width="960" style="display: block; margin: auto;" /></p>
<p><em>Wordcloud</em> untuk review hotel tersebut untuk melihat kata-kata yang paling sering muncul dalam ulasan wisatawan.</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb97-1"><a href="travel-and-accomodation.html#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Draw WordCloud</span></span>
<span id="cb97-2"><a href="travel-and-accomodation.html#cb97-2" aria-hidden="true" tabindex="-1"></a>wordcloud_draw(search_data[<span class="st">&#39;Review&#39;</span>].values[<span class="dv">0</span>].split(),<span class="st">&#39;white&#39;</span>)</span></code></pre></div>
<p><img src="bookmlindustry_files/figure-html/unnamed-chunk-3-33.png" width="672" style="display: block; margin: auto;" /></p>
<p>Fungsi untuk mengekspor dataset yang telah diolah untuk pembuatan dashboard.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode python"><code class="sourceCode python"><span id="cb98-1"><a href="travel-and-accomodation.html#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co">#df_merge.to_csv(&#39;dashboard_data.csv&#39;)</span></span>
<span id="cb98-2"><a href="travel-and-accomodation.html#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="co">#df_merge.to_excel(&#39;dashboard_data.xlsx&#39;)</span></span></code></pre></div>
<p>Hasil dari dashboard yang telah dirancang dapat dilihat di laman berikut: <a href="https://europehoteldashboard.herokuapp.com/" class="uri">https://europehoteldashboard.herokuapp.com/</a></p>
</div>
<div id="conclusion-6" class="section level3" number="9.1.5">
<h3><span class="header-section-number">9.1.5</span> Conclusion</h3>
<p>Hasil dari analisis ini berupa dashboard yang dapat digunakan para wisatawan untuk menentukan hotel mana yang terbaik dipilih sebagai tempat tinggal sementara selama menikmati liburan. Tentunya dengan adanya dashboard ini, diharapkan para wisatawan mendapatkan pengalaman terbaik dalam menginap. Dashboard ini menampilkan penilaian tidak hanya melalui <em>rating score</em> tapi juga mengenai nilai sentimen para wisatawan terdahulu terkait fasilitas-fasilitas dan pelayanan pada hotel tersebut. Fasilitas-fasilitas dan pelayanan yang menjadi aspek penilaian antara lain ruangan, staf hotel, kolam renang, kamar mandi, restoran, pemandangan, pelayanan, dan sarapan.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="media.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"],
"google": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
},
"all": null
});
});
</script>

</body>

</html>
